### ISSUE TITLE
Compatibility with shadow root (Chrome 70 and Firefox 63)

### ISSUE THREAD

**Issue by LT-AMC** [stefanuebe/vaadin_fullcalendar#1]
Hi, your component is exactly what we were looking for, but we were not able to get your example code to work with browsers that implement shadow root, so Chrome and Firefox since version 63.
We copied your Demo.java file and moved the demo-style.html to the correct position in our project.
The div with class "fc-scroller fc-day-grid-container" has a height of 0px when we open the calendar.

![grafik](https://user-images.githubusercontent.com/39570807/47577808-1780f480-d948-11e8-87d7-276c7cae2bd8.png)

We noticed that your online demo works just fine, so maybe we are just doing something wrong in our project?

**Comment by stefanuebe** [comment]
Have you checked under sources, if the demo-style.html file is loaded? I had the same problem, when the body element was not `display: flex` + `flex-direction: column` (need to find a better way for that, but currently it works somehow, at least in chrome 70 and newest ff).

Can you maybe provide me a copy of your implementation (e.g. via a repo fork or mail)?

**Comment by stefanuebe** [comment]
I'm currently working on setting the height by method on server side. Currently it seems to be a ungood combination when calculating the height by parent and the parent is a relative sized block displayed component (e.g. a div with height: 100%), while working with a block component + fixed height or flex component + height by parent seem to work without problems.

**Comment by stefanuebe** [comment]
Please have a look at the alpha 2. There are now height methods. I also updated (and refactored) the demo to provide a dialog for some display: block/flex + calendar height examples and also added a few code samples to the addon site.

If the problem still occurs, please re-open this issue. :)

**Comment by LT-AMC** [comment]
Being able to set the height has fixed our issues. Thanks for all the updates, great work!
