### ISSUE TITLE
Enhancement request: support false and/or local as timezone

### ISSUE THREAD

**Issue by martinisraelsen** [stefanuebe/vaadin_fullcalendar#11]
FC supports "false" (no timezone) and "local" as timezone options. This will make it much easier to use the calendar in situation where the app doesn't care about the user's timezone. 

https://fullcalendar.io/docs/timezone

**Comment by martinisraelsen** [comment]
Was playing around with timezones a little more, and I think there might be a problem somewhere in the demo or the calendar. 

I'm in US central time (CST6CDT) and the times shown in the demo doesn't match the code. The demo specifies 20:30 and it's showing as 2:30 PM (14:30) in the calendar. I would think that since the demo doesn't set the timezone, it should either be UTC or the browser's timezone.

Note - this is running the demo from Stefan.app.fi - not running it locally.

![screen shot 2018-11-16 at 10 39 44 pm](https://user-images.githubusercontent.com/6271003/48656933-0a0fd500-e9f1-11e8-83c7-c20d73fc4eca.png)
![screen shot 2018-11-16 at 10 39 52 pm](https://user-images.githubusercontent.com/6271003/48656934-0a0fd500-e9f1-11e8-9d6a-8c3e7713c884.png)

**Comment by stefanuebe** [comment]
Did it work?
