### ISSUE TITLE
Overnight recurring events not possible

### ISSUE THREAD

**Issue by FDotterweich** [stefanuebe/vaadin_fullcalendar#115]
### Bug Description

According to [this stackoverflow post](https://stackoverflow.com/questions/32136130/recurring-overnight-events-in-fullcalendar/32145493#32145493) overnight recurring events can be created in FullCalendar using an endTime that is greater than 24:00. 
It seems to be impossible to do this using this AddIn since recurringEndTime is set via java.time.LocalTime which is limited to 23:59:59:999999999. 

### Example Code (Kotlin)

    calendar.addEntry(Entry().apply {
        title = "test title"
        description = "test via UI"
        isRecurring = true
        recurringDaysOfWeeks = setOf(DayOfWeek.MONDAY, DayOfWeek.THURSDAY)
    
    
        recurringStartDate = LocalDateTime.now().minusDays(30).toInstant(ZoneOffset.UTC)
        recurringEndDate = LocalDateTime.now().plusDays(30).toInstant(ZoneOffset.UTC)
    
        recurringStartTime = java.time.LocalTime.of(18, 0, 0)
        recurringEndTime = recurringStartTime.plusHours(8)
    })

When I execute the above code the following entry is generated:

Entry(id=37963830-e0fa-4523-8848-6142b36f5872, title=test title, start=null, end=null, allDay=false, classNames=[], editable=true, startEditable=false, durationEditable=false, color=null, customProperties={}, renderingMode=NONE, recurring=true, recurringDaysOfWeeks=[MONDAY, SATURDAY], recurringStartDate=2021-10-10T15:43:40.001127800Z, **recurringStartTime=18:00**, recurringEndDate=2021-12-09T15:43:40.001127800Z, **recurringEndTime=02:00**, groupId=null)'

Since the truncated recurringEndTime is before the recurringStartTime the entry is not displayed at all. I would expect that the entry goes from 18:00 to **02:00 the next day**.

A possible solution could be to use startTime & duration instead of startTime & endTime...?

**Comment by stefanuebe** [comment]
With the next minor release, it should be possible to do that the following, low-level way. An official supporting high-level api might follow in future.

```
LocalDate now = LocalDate.now();

ResourceEntry recurring = new ResourceEntry();
recurring.setTitle(now.getYear() + "'s monday event");
recurring.setColor("lightgray");
recurring.setRecurringDaysOfWeek(Collections.singleton(DayOfWeek.MONDAY));

recurring.setRecurringStartDate(now.with(TemporalAdjusters.firstDayOfYear()), calendar.getTimezoneClient());
recurring.setRecurringEndDate(now.with(TemporalAdjusters.lastDayOfYear()), calendar.getTimezoneClient());

recurring.set(Entry.EntryKey.RECURRING_START_TIME, "13:00");
recurring.set(Entry.EntryKey.RECURRING_END_TIME, "37:00");

recurring.setResourceEditable(true);

calendar.addEntry(recurring);
```

**Comment by stefanuebe** [comment]
@see https://github.com/stefanuebe/vaadin_fullcalendar/issues/112

**Comment by stefanuebe** [comment]
Version 3.2.0 released, above mentioned approach should now be doable.
