### ISSUE TITLE
setEntryRenderCallback missing

### ISSUE THREAD

**Issue by mheicke** [stefanuebe/vaadin_fullcalendar#120]
Thanks for the great work 👍 

To me it seems that the **setEntryRenderCallback** in `org.vaadin.stefan.fullcalendar.FullCalendar` is missing version 3.0 and above - is this correct? What would be the right way to inject code into the renderer mechanism?

Example code would be 
```  
calendar.setEntryRenderCallback("" +
      "function(event, element) {" +
      "   console.log(event.title + 'X');" +
      "   element.css('color', 'red');" +
      "   return element; " +
      "}");
```

I have the feeling that it is replaced by `setEntryContentCallback` but I can't find any documentation example for this

**Comment by stefanuebe** [comment]
Yes, it is now named setEntryContentCallback. A detailed description on how it can be used can be found here: https://fullcalendar.io/docs/content-injection (under "a function that returns any of the above formats:")

**Comment by stefanuebe** [comment]
(also update the directory sample)
