### ISSUE TITLE
color of active button cannot be set (only background color)

### ISSUE THREAD

**Issue by willemv** [stefanuebe/vaadin_fullcalendar#121]
### Bug Description

This addon does not provide the custom css property to set the text color of the active buttons in the fullcalendar. You can only set the background color.

I.e. this property works : `--fc-button-active-bg-color: var(--lumo-primary-color)`
But this will not be taken into account : `--fc-button-active-text-color: var(--lumo-body-text-color)`

That's because [this line](https://github.com/stefanuebe/vaadin_fullcalendar/blob/master/addon/src/main/resources/META-INF/resources/frontend/full-calendar.js#L248) uses the `--fc-button-text-color` css property, which is not appropriate IMO.

**Comment by stefanuebe** [comment]
The native full calendar buttons are not officially supported by the Flow addon, instead we recommend to use Flow components for interaction with the calendar. Also the css variables are more or less just a automatic generated helper for simple styling. If you want to other custom styles, we recommend either to subclass the full calendar or apply the styles via the Java api. Unfortunately shadow dom and custom styling still are natural enemies.

See the examples "Modifiy FC's appearance by using a custom class" or "Modify FC's appearance by adding a style element using Element API" (on the directory page) for details
