### ISSUE TITLE
Tooltip event

### ISSUE THREAD

**Issue by simasch** [stefanuebe/vaadin_fullcalendar#122]
Hi, thanks for this very useful component!

I tried to add a tooltip but failed with

    this.getCalendar().setOption("eventRender", this.callTooltip);

But using eventDidMount works:

    this.getCalendar().setOption("eventDidMount", this.callTooltip);

Is this just my problem or the problem of the example?

**Comment by aetasoul** [comment]
Hi @simasch the problem is the [example](https://github.com/stefanuebe/vaadin_fullcalendar/wiki/FullCalendar-Examples#using-tippyjs-for-description-tooltips), is not up to date (it's related to the V4 of the calendar)

We'll fix this soon, thank you!

**Comment by aetasoul** [comment]
All done

**Comment by simasch** [comment]
Thanks @aetasoul
