### ISSUE TITLE
Overhaul code samples

### ISSUE THREAD

**Issue by stefanuebe** [stefanuebe/vaadin_fullcalendar#123]
Tend to be outdated here and there.

**Comment by stefanuebe** [comment]
Also provide release nots

**Comment by stefanuebe** [comment]
Readme samples and introduction overhauled.

**Comment by aetasoul** [comment]
Do you prefer to keep updated the readme as wiki or use the wiki of github?

Maybe we can use the readme to present the addon and redirect to the wiki for the examples and more

**Comment by stefanuebe** [comment]
> Maybe we can use the readme to present the addon and redirect to the wiki for the examples and more

Yes that's a good idea. I always forget about the wiki again :D

**Comment by stefanuebe** [comment]
Updated the readme and wiki. Also extracted the samples into two separate files for easier maintenance. Any other additional info has been removed from there and kept in the wiki to prevent having two sources of truth.

**Comment by stefanuebe** [comment]
Todo: update the samples, when releasing 4.0.0.

**Comment by stefanuebe** [comment]
Added a migration guide: https://github.com/stefanuebe/vaadin_fullcalendar/wiki/FullCalendar-MigrationGuides

@aetasoul may you have time to give it a brief review?

**Comment by aetasoul** [comment]
Yes, tomorrow I'll take a look at it

**Comment by stefanuebe** [comment]
Also there is a simple list of release notes, not sure if something is missing there: https://github.com/stefanuebe/vaadin_fullcalendar/wiki/FullCalendar-ReleaseNotes

**Comment by aetasoul** [comment]
> Also there is a simple list of release notes, not sure if something is missing there: https://github.com/stefanuebe/vaadin_fullcalendar/wiki/FullCalendar-ReleaseNotes

Release note ok

**Comment by aetasoul** [comment]
> Added a migration guide: https://github.com/stefanuebe/vaadin_fullcalendar/wiki/FullCalendar-MigrationGuides
> 
> @aetasoul may you have time to give it a brief review?

All ok also here, just added a link
