### ISSUE TITLE
Validate the current usage of timezones when transporting dates between client and server

### ISSUE THREAD

**Issue by stefanuebe** [stefanuebe/vaadin_fullcalendar#126]
Check, if it is necessary, that dates are converted to the client timezone on the server before sent to the client or if sending them as UTC might be enough and though they can be converted to the client timezone on client.

While the functionality should not change, this might increase performance when changing the timezone (which may happen initially and therefore lead to an additional resending of all items, after the browser timezone has been captured for instance)

**Comment by stefanuebe** [comment]
Reason for this issue is, that when adding for instance 3k items, the current way of updating the items server > client will basically freeze the browser.

**Comment by stefanuebe** [comment]
See branch `timezone_date_transport`

**Comment by stefanuebe** [comment]
Todo: check, if parsing a date only value should always produce a date time string (e.g. view render event)

**Comment by stefanuebe** [comment]
Second thing to check is, if LocalDate/LocalDateTime should be 
a) provided at all as api and if, then
b) if they really should rely on the server time zone to be converted to or simply represent the same value as UTC.

Based on the changes of 
https://github.com/stefanuebe/vaadin_fullcalendar/issues/110

Thought about this topic now several times, also https://stackoverflow.com/questions/32437550/whats-the-difference-between-instant-and-localdatetime/32443004#:~:text=Instant%20and%20LocalDateTime%20are%20two,class%20cannot%20represent%20a%20moment. adds some thoughts to it.

Question is, if Instant is really used by most developers or if they tend to use LocalDate(Time). Next question is, how do developers interprete LocalDate(Time).

While LocalDate is more or less relative simple in respect to the FC (I am going to behave like the client side and google calendar, where a day is a day, no matter of the timezone), going into LocalDateTime and also LocalTime it starts to become more interesting.

Not sure about that yet, just wanted to note my current thoughts.

**Comment by stefanuebe** [comment]
The branch timezone_remove_instant shows an approach, where the server side operates only on UTC based dates. Currently all Instants are commented out, but maybe will be returned parallel to the local date time (since both will be utc)

**Comment by stefanuebe** [comment]
@aetasoul any thoughts on this topic? (if it makes sense at all)

**Comment by stefanuebe** [comment]
Important here is, that the current implementation has one big flaw. That is, that we convert the entry times to the client timezone on the server instead of simply sending them as UTC and then let FC do the conversion. I tested it and works perfectly. This means, that the server side itself never needs to do any conversion at all. 

> The conversion on the client side will simplfy the developers?

In theory it simplifies it as mentioned above, that we do not have to take care of converting anything. All times on server side will be UTC based. If there is any application of the client timezone is necessary (e.g. to show it in a dialog for editing as we do now), the UTC based time needs to be modified with the respective zone offset. For that we can provide convenience methods inside the Timezone class. 

e.g.
```
Entry entry = ... // get the entry to edit from somewhere
LocalDateTime utcDateTime = entry.getStart(); // could also be Instant, not sure yet. e.g. 1.1.2020, 13:00 
Timezone someTimezone = calendar.getTimezoneClient(); // e.g. Los Angeles (-8h to UTC)

LocalDateTime dateTimeWithOffset = someTimezone.addZoneOffset(utcDateTime) // resulting LDT is 1.1.2020, 05:00
DatePicker datePicker = ... // get the date picker from somewhere

datePicker.setValue(dateTimeWithOffset);

// ... 

dateTimeWithOffset  = datePicker.getValue();
utcDateTime  = someTimezone.removeZoneOffset(utcDateTime)
entry.setStart(utcDateTime).
```

The above sample shows the difference to the current approach. In the current implementation all LocalDateTime API is always including the zone offset to the utc time, which is somehow reasonable and on the other hand not, since LocalDateTime has no offset or anything like that. This means, that based on the perspective, it can be misunderstood somehow. This also led indirectly to issue #110 , which I just realized yesterday is also somehow one way of approaching, but somehow also a false approachment. 

To get rid of interpreting, what that LocalDateTime could mean, when working with entries, I would simply say, that any time we set on the server side is ALWAYS utc based, regardless wheter it is LocalDateTime or Instant. In that way, the developers are free to convert the times to any format they need without needing to check beforehand, if the value is maybe offsetted by some timezone or not. If you want to store the values in a database, you have nothing to convert. If you want to allow editing it, you simply can offset or "un-offset" the given time using the client side timezone instance.

> What happens if I create an event in Italy and then go on vacation to Mexico? The event on the client side will be in mexican timezone, so could be useful or not? It depends.

For the user nothing changes. They can switch the timezone as they can now (as in the FullDemo for instance), since FC already handles the entries internally as UTC and converts them as necessary. The only change is, that we do not resend all entries on every timezone change as we do now, since it is no longer necessary. 

Currently the entry date times always are offsetted with the respective timezone, thus they theoretically need to be resend to the client, when the offset changes. When sending them as utc timestamps, this is no longer necessary.

So the Italian guy still can simply use a dropdown do see how his times may change, when he moves to Mexico :) 

> We can add a way to force the client timezone from the server side? 

That we already can do. That will not change. So yesterday, today and tomorrow the server side is able to change the timezone (as we do in the timezone combobox already).

Difference is, as stated above, that no data needs to be resend to the client in that case, as every communication between server and client will be utc based.

One important side note:

Also one change will be, that LocalDates will no longer be affected by the timezone, since dates do not have a timezone. This may be a bit strange in the first view, but that is the normal behavior of all "big" calenders. Google acts that way and the FullCalendar demos also. Only we do not. So for instance, if I have a holiday, that is on monday, then that holiday is on monday, regardless of the timezone you are in. But in the current implementation, that holiday will stretch over sunday to monday, when I move to some other timezone for instance. That is a bug, that also will be fixed with this implementation.

**Comment by stefanuebe** [comment]
> Personally I prefer to use LocalDate(Time)
> I use postgres as database with one column for the event datetime as timestamp without time zone, the Dao to handle the DB work with LocalDateTime, and I convert the value before send it to the client side.

Me, too. Most API is LocalDate(Time) based. In most cases it is fine. I will keep Instant to not have too many breaking changes, but my current approach is to use LocalDateTime again internally. The initial issue #7 and it also comes from the times, where the server side converts LDT already to the client side.

**Comment by stefanuebe** [comment]
But that all is currently theoretical thinking. It might be, that there is some usecase or scenario I haven't thought of, where it makes sense, that entries are sent to the client already having a timezone offset on the start/end time

**Comment by stefanuebe** [comment]
Following ideas / changes in short:

* transport of times is only done as utc
* server keeps times only as utc
* entry api provides/takes times as utc (getStart/setStart...)
* Timezone provides APIs to add or remove its offset to a LocalDateTime. Use case here is to convert times from and to UTC
* entry may have a custom start and end timezone. these are transported to the client and applied only there. (later feature)
* Calendar only provides a get/setTimezoneClient, which will set the respective option in the FC. No further data is sent to the client. The FC / client side takes completely care of updating the displayed entries based on the given timezone (currently FC does that automatically)

For the entry we may provide additional api as we have now to support direct timezone support, but it should be named more concrete, e.g. 
* get/setStart - handles entry start as local date time with the meaning of UTC based time
* get/setStartAsInstant - same as getStart but returns an instant UTC
* getStartWithClientTimeZone - returns a ZonedDateTime (where the dev can for instance use toLocalDateTime to use it in the api). Alternativeley we could directly return a LocalDateTime, which has the offset added. Not sure yet, which is more concrete or more "clear". ZonedDateTime is at least the official approach of Java. Question is, how can we provide easy access to set that value after some outside change without having the dev need to use ZonedDateTime or take care of any offsetting. Something to prototype.
* getStartWithTimeZone - same as getStartWithClientTimeZone but with a custom time zone. Not sure if really needed? 

Since that all is a huge change, it will lead to a new major version 4.x of the FC.

**Comment by aetasoul** [comment]
> Following ideas / changes in short:
> 
> * transport of times is only done as utc
> * server keeps times only as utc
> * entry api provides/takes times as utc (getStart/setStart...)
> * Timezone provides APIs to add or remove its offset to a LocalDateTime. Use case here is to convert times from and to UTC
> * entry may have a custom start and end timezone. these are transported to the client and applied only there. (later feature)
> * Calendar only provides a get/setTimezoneClient, which will set the respective option in the FC. No further data is sent to the client. The FC / client side takes completely care of updating the displayed entries based on the given timezone (currently FC does that automatically)
> 
> For the entry we may provide additional api as we have now to support direct timezone support, but it should be named more concrete, e.g.
> 
> * get/setStart - handles entry start as local date time with the meaning of UTC based time
> * get/setStartAsInstant - same as getStart but returns an instant UTC
> * getStartWithClientTimeZone - returns a ZonedDateTime (where the dev can for instance use toLocalDateTime to use it in the api). Alternativeley we could directly return a LocalDateTime, which has the offset added. Not sure yet, which is more concrete or more "clear". ZonedDateTime is at least the official approach of Java. Question is, how can we provide easy access to set that value after some outside change without having the dev need to use ZonedDateTime or take care of any offsetting. Something to prototype.
> * getStartWithTimeZone - same as getStartWithClientTimeZone but with a custom time zone. Not sure if really needed?
> 
> Since that all is a huge change, it will lead to a new major version 4.x of the FC.

Agree with all the changes.

About the entry, for now I never needed to customize the timezone for the single entry, it's better to wait for the request from some dev before implement that.

**Comment by stefanuebe** [comment]
@aetasoul 

I pushed a first draft of the new start / end api to the branch "timezone_remove_instant". The branch name makes no sense at all related to the last changes and after changing everything it appears, that the changes are not that huge regarding the API, but the use of LocalDateTime only. :D 

Also haven't tested the demo for runnability yet, but ran the tests (they ran through). If you have a few minutes today or tomorrow to give the changes a brief review, I would be most grateful :)

**Comment by stefanuebe** [comment]
@kamuffe

This issue/topic might be interesting for you, too?

**Comment by aetasoul** [comment]
> @aetasoul
> 
> I pushed a first draft of the new start / end api to the branch "timezone_remove_instant". The branch name makes no sense at all related to the last changes and after changing everything it appears, that the changes are not that huge regarding the API, but the use of LocalDateTime only. :D
> 
> Also haven't tested the demo for runnability yet, but ran the tests (they ran through). If you have a few minutes today or tomorrow to give the changes a brief review, I would be most grateful :)

I'll take a look at this as soon as possibile and let you know!

**Comment by aetasoul** [comment]
@stefanuebe 

I add the holidays to the calendar as bg event, and to make some beautiful changes to the event design etc I  set a custo property called isHoliday as: `entry.setCustomProperty("isHoliday", true);`

Now this lead in `(TypeError) : Cannot read properties of undefined (reading 'isHoliday')`

I'll investigate it as soon as possible, the problem is not present with the version 3.2.1 so it generate after the commit 4e4fa9c9 or maybe I just do something wrong changing the code to fit the 4.0.0-snapshot

The timezone changes seems to be ok but I first need to fix this error or all the calendar that I use to test can't correctly load

___

The demo seems to be ok with the changes, the only think that dosn't work anymore is the Tooltip example, but seems to be broken also on the official demo (https://stefan.app.fi/fullcalendar-demo/tooltip) so for the master branch. I'll cover this with a separate issue.

**Comment by stefanuebe** [comment]
Hmmmm. Is the issue appearing on an entry, that has the custom property set or that has it not set? And how do you access the custom property? I removed "accidentally" the customProperties from the client side, but theoretically it should be readded / restored. So, custom properties should be accessible using the "maybe" operator (`some?.key`)

```
event.extendedProps.customProperties
```

The "custom properties" demo seems to work, using
```
calendar.setEntryContentCallback("" +
            "function (info) {" +
            "	if (info.event.extendedProps?.customProperties?.selected)" +
            "		info.backgroundColor = 'lightblue';" +
                "else " +
            "		info.backgroundColor = 'lightgreen';" +
            "	" +
            "}");
```

**Comment by stefanuebe** [comment]
If the issue still occur, can you please check in the sample code as a demo?

**Comment by aetasoul** [comment]
Problem is still present, too hard to convert my code as demo. Let me debug it, but i'm pretty sure is my code fault and to the calendar

**Comment by aetasoul** [comment]
Found the problem, I just missed to remove one timezone from one entry, for another bug in my code when the entry on the DB is not found it create an empty entry, this generate the exception, because the empty entry are ignored and the is no isHoliday assignement and for another bug the javascript call an hidden and forgotten function that I wrote years ago that doesn't check if isHoliday exist or not.

Definetly my code fault, all the changes are good. 

I checked some entries on my calendar and is all good!

**Comment by stefanuebe** [comment]
:: offtopic
@aetasoul the tooltip is now fixed and I also added some js to extend the client side FC event with a `getCustomProperty` method so that the devs do not need to use some internal properties, that may or may not be initialized correctly.

Usage is for instance 

```
let event = ...

event.getCustomProperty("hello") // returns either the custom property value or undefined
event.getCustomProperty("hello", "world") // returns either the custom property value or "world", if the cp value is undefined
```

See full-calendar-with-tooltip.js as a sample. Can you please check, if this approach also works with your demo?

**Comment by stefanuebe** [comment]
:: offtopic
@aetasoul the tooltip is now fixed and I also added some js to extend the client side FC event with a getCustomProperty method so that the devs do not need to use some internal properties, that may or may not be initialized correctly.

See https://github.com/stefanuebe/vaadin_fullcalendar/issues/132 for details.

**Comment by aetasoul** [comment]
> :: offtopic @aetasoul the tooltip is now fixed and I also added some js to extend the client side FC event with a getCustomProperty method so that the devs do not need to use some internal properties, that may or may not be initialized correctly.
> 
> See #132 for details. Can you please countercheck, if that new api is also working in your example?

Hi @stefanuebe 
Checked all and is fine, see #132 for details

**Comment by stefanuebe** [comment]
@aetasoul 

I created a new branch v4.0.0_dev as the "main" branch for the 4.0.0 dev to have a better naming regarding the changes.

The timezone_remove_instant will be outdated from now on.

**Comment by stefanuebe** [comment]
Done. 4.0 is released. Thank you @aetasoul :)
