### ISSUE TITLE
Provide easier access to custom properties on client side

### ISSUE THREAD

**Issue by stefanuebe** [stefanuebe/vaadin_fullcalendar#132]
Currently a custom property on client side has to be access like 
```
event.extendedProps.customProperties[key]
```

This is unreadable, hard to type and error prone.

Events should provide a method `getCustomProperty` to easily access the properties.

**Comment by stefanuebe** [comment]
Added some js to extend the client side FC event with a `getCustomProperty` method so that the devs do not need to use some internal properties, that may or may not be initialized correctly.

Usage is for instance 

```
let event = ...

event.getCustomProperty("hello") // returns either the custom property value or undefined
event.getCustomProperty("hello", "world") // returns either the custom property value or "world", if the cp value is undefined
```

See full-calendar-with-tooltip.js as a sample. 

Attention: unfortunately there is no technical / internal "event object" create hookback, but only the [render hooks](https://fullcalendar.io/docs/event-render-hooks) (at least from what I found so far), to access the final event object, before rendering. 

Therefore there is a bit of hacking into the calendar api to allow extending the event object with such a function and this method is earliest available with "eventContent" / "eventDidMount". There might be a better way in future.

**Comment by aetasoul** [comment]
Hi @stefanuebe,
all good. There are just some summary that use the old extendedProps

https://github.com/stefanuebe/vaadin_fullcalendar/blob/timezone_remove_instant/addon/src/main/java/org/vaadin/stefan/fullcalendar/Entry.java#L1101

https://github.com/stefanuebe/vaadin_fullcalendar/blob/timezone_remove_instant/addon/src/main/java/org/vaadin/stefan/fullcalendar/Entry.java#L1114

https://github.com/stefanuebe/vaadin_fullcalendar/blob/timezone_remove_instant/addon/src/main/java/org/vaadin/stefan/fullcalendar/Entry.java#L1132

https://github.com/stefanuebe/vaadin_fullcalendar/blob/timezone_remove_instant/addon/src/main/java/org/vaadin/stefan/fullcalendar/Entry.java#L1182

___

As second step we can update the resource object to replace the old extendedProps with the new customProps logic, what do you think?

**Comment by aetasoul** [comment]
Previously on the test the expected value was NONE `Assertions.assertEquals(RenderingMode.NONE, entry.getRenderingMode());` but now the default value for getRenderingMode is AUTO,

just update the line 610 of entrytest file in addon `Assertions.assertEquals(RenderingMode.AUTO, entry.getRenderingMode());` 

or maybe is better to restore the default value as NONE?

**Comment by aetasoul** [comment]
Updated the test as `Assertions.assertEquals(RenderingMode.AUTO, entry.getRenderingMode());` and replaced most of the references to extendedProps  with customProps

**Comment by stefanuebe** [comment]
> Previously on the test the expected value was NONE `Assertions.assertEquals(RenderingMode.NONE, entry.getRenderingMode());` but now the default value for getRenderingMode is AUTO,
> 
> just update the line 610 of entrytest file in addon `Assertions.assertEquals(RenderingMode.AUTO, entry.getRenderingMode());`
> 
> or maybe is better to restore the default value as NONE?

Since none means the entry is not displayed, I changed it to auto. Thanks for the corrections

**Comment by stefanuebe** [comment]
(at least based on the fc docs :) )

**Comment by aetasoul** [comment]
yes, it's better like this
