### ISSUE TITLE
Wiki: error in code example

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#134]
### Bug Description

We need to extend the Entry class and using the following example to achieve that.

In the following wiki there is a syntax error:
https://github.com/stefanuebe/vaadin_fullcalendar/wiki/FullCalendar-Examples

**Section**: Use the low level JsonItem API to modify a calendar item

```
public class ExtendedEntry extends Entry {

    private static final Set<Key> KEYS = Key.readAndRegisterKeysAsUnmodifiable(ExtendedKey.class);

    @Override
    public Set<Key> getKeys() {
        return KEYS;
    }

    public boolean isFoo() {
        return get(KEY_FOO , false); // alternatively we can use native based methods like getBoolean(Key)
    }

    public void setFoo(boolean foo) {
        set(KEY_FOO , foo);
    }

   public static class ExtendedKey extends EntryKey {
       private static final KEY_FOO = JsonItem.Key.builder()
           .name("foo")
           .updateFromClientAllowed(true)
           .build();
   }
}
```

1. The `private static final KEY_FOO = JsonItem.Key.builder()` in the ExtendedKey class is missing the type `Key`.

2. I cannot call `private static final Set<Key> KEYS = Key.readAndRegisterKeysAsUnmodifiable(ExtendedKey.class);` since Key.readAndRegisterKeysAsUnmodifiable is protected. Should this method be public?

Best,
Kamuffe

**Comment by stefanuebe** [comment]
Should both be fixed now (with version 4.0.3).
