### ISSUE TITLE
Remove Header Toolbar

### ISSUE THREAD

**Issue by Juchar** [stefanuebe/vaadin_fullcalendar#14]
As most of the time we will control the calendar using vaadin controls, it would be nice if the space for the header toolbar could be removed by using:
 ```
.fc-toolbar.fc-header-toolbar {
      display: none;
    }
```

Alternative would be to make the component themable using [Themable Mixin](https://github.com/vaadin/vaadin-themable-mixin).

**Comment by stefanuebe** [comment]
Solved this problem by setting the `header` option to `false` instead empty objects. This removes the toolbar space.

Will be contained in addon version 1.9.1
