### ISSUE TITLE
EntryProvider for ResourceEntry

### ISSUE THREAD

**Issue by ARCHERS** [stefanuebe/vaadin_fullcalendar#141]
LazyInMemoryEntryProvider is provided to lazy load FullCalendar from a database. However there is no equivalent method for Calendar Scheduler, which needs to extend ResourceEntry instead of Entry. It would be nice to see this implemented.

**Comment by stefanuebe** [comment]
Can you please examine in detail why you need an explicit ResourceEntry support, e. g. use cases, any issues or similar? Since the in memory / crud api been taken from the Full Calendar, I would not have expected any issues here.

**Comment by stefanuebe** [comment]
The following code leads to an compiler issue since setEntryProvider only accepts `EntryProvider<Entry>`

List<ResourceEntry> entryList = myService.streamResourceEntries().collect(Collectors.toList());
LazyInMemoryEntryProvider<ResourceEntry> entryProvider = EntryProvider.lazyInMemoryFromItems(entryList);
calendar.setEntryProvider(entryProvider);

**Comment by stefanuebe** [comment]
Workaround for now is to cast the list given to the entry provider to `List`, e. g.

List<ResourceEntry> entryList = myService.streamResourceEntries().collect(Collectors.toList());
LazyInMemoryEntryProvider<ResourceEntry> entryProvider = EntryProvider.lazyInMemoryFromItems((List) entryList);
calendar.setEntryProvider(entryProvider);

**Comment by stefanuebe** [comment]
Released in 4.1.2

**Comment by ARCHERS** [comment]
Thanks - I tried the cast to List, but it still doesn't compile due to the Entry requirement for calendar. My application involves allocating clinic appointments to different meeting rooms (resources) because they run in parallel. So the EntryProvider seemed like a more efficient way of lazy loading the calender with ResourceEntries rather than iterating through a list and doing calender.addEntry.  I'll have a look at it again if there's no easy workaround.

**Comment by stefanuebe** [comment]
Ok. Please try if the new release fixes your problem.

**Comment by ARCHERS** [comment]
Thanks for the Entity Provider fixes in 4.1.2. All working nicely.
