### ISSUE TITLE
 No DayHeader in ResourceTimeGridDay

### ISSUE THREAD

**Issue by ARCHERS** [stefanuebe/vaadin_fullcalendar#144]
When using Scheduler, there does not seem to be a DayHeader by default in the ResourceTimeGridDay, but it's present in ResourceTimeGridWeek. I couldn't see how to add it from Flow.

Thanks for your help.

**Comment by aetasoul** [comment]
I don't think dayHeader would appear on a day view

https://fullcalendar.io/docs/dayHeaders

Anyway to set it  to true for the view: `calendar.setOption("dayHeaders", true);`

**Comment by ARCHERS** [comment]
Thanks for the links and I've seen how it is displayed in all the demos.

You are correct that calendar.setOption("dayHeaders", true) doesn't work.

It doesn't make sense to me not to have dayHeader included for resourceTimeGridDay when it is included for TimeGridDay, TimeGridWeek and resourceTimeGrid Week. I don't use the default FullCalendar toolbar with a date field, I have instead created by own side toolbar, so I really need to see the dates in a dayHeader.

**Comment by aetasoul** [comment]
Thare is alredy an open issue: https://github.com/fullcalendar/fullcalendar/issues/5740

**Comment by ARCHERS** [comment]
OK thanks - I'll follow it up there.
