### ISSUE TITLE
New Line in Entry Title

### ISSUE THREAD

**Issue by ARCHERS** [stefanuebe/vaadin_fullcalendar#145]
How do you create a new line in Entry Title? Adding \n or html to the title string doesn't seem to work . As per the example at https://codepen.io/acerix/pen/YzyrwJV, I tried the following without success:

```
calendar.setEntryContentCallback("" +
    "function(arg) {" +
    "   return {html: arg.event.title.replace(/\\n/g, '<br>')}" +
    "}"
    );
```

Can you help?

**Comment by aetasoul** [comment]
Hi @ARCHERS 

Using your codepen sample it's working the `\n`:

I just edited the events array and placed in the title the `\n` and updated the start date
```
events: [
      {
        title: 'All\nDay Event',
        start: '2022-03-01'
      }
    ]
```

**Comment by ARCHERS** [comment]
Thanks. However the \n does not work for me using entry.setTitle(). I'm using ResourceEntry and FullCalendar/Scheduler version 4.1.2. Which version are you using - could there be a difference?

**Comment by aetasoul** [comment]
Probably yes, I'm updating now and it stopped working.

Let me check

**Comment by aetasoul** [comment]
This is the best way that I found to have the new line: `calendar.addCustomStyles(".fc-event-title{white-space: normal;}");

![image](https://user-images.githubusercontent.com/15131692/159747172-ea08b590-bd1e-41c1-b229-144b2b4caf53.png)

**Comment by ARCHERS** [comment]
Great that works - so if I use: ``` calendar.addCustomStyles(".fc-event-title{white-space: pre-line;}"); ```
then I get a line break with \n. ``` calendar.addCustomStyles(".fc-event-title{white-space:normal;}"); ``` wraps the text according to space as expected but ignores new line break.

Thanks for your help.

**Comment by stefanuebe** [comment]
> Hi @ARCHERS
> 
> Using your codepen sample it's working the `\n`:
> 
> I just edited the events array and placed in the title the `\n` and updated the start date
> 
> ```js
> events: [
>       {
>         title: 'All\nDay Event',
>         start: '2022-03-01'
>       }
>     ]
> ```
> 
> To make it work in Flow I did nothing, just placed in the title the `\n`.
> 
> ```java
> entry.setTitle("My title \n with new line")
> ```
> 
> Try to remove `setEntryContentCallback`

In which version did it work for you?

**Comment by aetasoul** [comment]
I thought it was on a recent version, but the project where I made the \n to work was made with the v4 of the calendar, so it was working before the v5 update

**Comment by aetasoul** [comment]
Version 3.1.0, I'm searching on the repo trough my phone but it's confusing

**Comment by stefanuebe** [comment]
Then it might be really "just", that they changed the basic whitespace styling with the new major version, which prevents setting simple new lines in the title

**Comment by aetasoul** [comment]
Yes, I'll check the CSS and search for it, but I think it's like this. I'd like to know so we can add it to the wiki

**Comment by jonasrotilli** [comment]
> Esta é a melhor maneira que encontrei de ter a nova linha:`calendar.addCustomStyles(".fc-event-title{white-space: normal;}");`
> 
> ![image](https://user-images.githubusercontent.com/15131692/159747172-ea08b590-bd1e-41c1-b229-144b2b4caf53.png)

How do I do this?
I'm using version 6.2.2.
I can't find calendar.addCustomStyles, it doesn't have that function.
Does anyone know how to use this? It's exactly what I need, for it to break automatically.

**Comment by jonasrotilli** [comment]
> > Esta é a melhor maneira que encontrei de ter a nova linha:`calendar.addCustomStyles(".fc-event-title{white-space: normal;}");`
> > ![image](https://user-images.githubusercontent.com/15131692/159747172-ea08b590-bd1e-41c1-b229-144b2b4caf53.png)
> 
> How do I do this? I'm using version 6.2.2. I can't find calendar.addCustomStyles, it doesn't have that function. Does anyone know how to use this? It's exactly what I need, for it to break automatically.

Does anyone know how to help me?

**Comment by stefanuebe** [comment]
Where do you have this method from? It is outdated since 6.x

Since this major version, the FC does not use a shadow dom anymore and thus styling can be done using normal css stylesheets: https://github.com/stefanuebe/vaadin-fullcalendar/wiki/FullCalendar-MigrationGuides#styling

**Comment by jonasrotilli** [comment]
> Where do you have this method from? It is outdated since 6.x
> 
> Since this major version, the FC does not use a shadow dom anymore and thus styling can be done using normal css stylesheets: https://github.com/stefanuebe/vaadin-fullcalendar/wiki/FullCalendar-MigrationGuides#styling

I took it from here, from the comments.

I'm certainly wrong, because if I were right I wouldn't need help.

Ok, I'll try to understand the documentation. But if someone has practical instructions on how to use it, it would be great for me, a beginner developer.

**Comment by jonasrotilli** [comment]
> > De onde você tirou esse método? Ele está desatualizado desde 6.x
> > Desde esta versão principal, o FC não usa mais um shadow dom e, portanto, o estilo pode ser feito usando folhas de estilo CSS normais: https://github.com/stefanuebe/vaadin-fullcalendar/wiki/FullCalendar-MigrationGuides#styling
> 
> Peguei daqui, dos comentários.
> 
> Certamente estou errado, porque se estivesse certo não precisaria de ajuda.
> 
> Ok, vou tentar entender a documentação. Mas se alguém tiver instruções práticas sobre como usá-la, seria ótimo para mim, um desenvolvedor iniciante.

I did it! To help with future questions, I added this to the CSS of the project, or the class that has the Calendar:
`.fc-event .fc-event-title {
  white-space: normal !important;
}`
While I was at it, I added a line to separate the items:
`.fc-event {
  border-bottom: 1px solid #e0e0e0 !important; /* Linha cinza clara */
  padding-bottom: 4px !important;
}`
