### ISSUE TITLE
Can't set Constraint property on Entry

### ISSUE THREAD

**Issue by ARCHERS** [stefanuebe/vaadin_fullcalendar#146]
From the FullCalendar js documentation, I note you can use "constraint" property on a timed event and link this to a background event with matching "groupId" property to get more granular control over where events can be dragged and dropped. I can set the groupId on the java side with entry.setGroupId, but there is no corresponding method for constraint such as "setConstraint". I tried creating a custom property like entry.setCustomProperty("constraint", "appointment"), but that doesn't work.

Can you help?

**Comment by aetasoul** [comment]
Hi @ARCHERS 

the setCustomProperty generate in a separate area the prop, is not for access the default entry props.

We'll add it in the next release

**Comment by ARCHERS** [comment]
Great thanks. I figured that was the case.

**Comment by aetasoul** [comment]
Hi @ARCHERS 
There is now an option for the entry to set the constraint as string, like shown on the calendar help page: `entry.setConstraint("business hours")`

In case you need to pass the resources for now you need to create an array of strings containing the IDs of the resources

**Comment by ARCHERS** [comment]
Thanks for that suggestion. Do you mean as shown on the Vaadin FullCalendar site, as I couldn't see any reference to an entry  constraint in the code samples. I know I can use calendar.setOption("eventConstraint", "businessHours") to set it globally.

**Comment by aetasoul** [comment]
Hi @ARCHERS the commit https://github.com/stefanuebe/vaadin_fullcalendar/commit/4974beb7bdc4c74bcc7450951b0dfee1bd1dbc77 add the `setContraint` for the entry.

Yout can assign to it a string, as shown on the fullcalendar docs (Not our wiki) https://fullcalendar.io/docs/eventConstraint

In case you need to pass the resources, as show in the section Resources, for now you need to create an array of strings containing the IDs of the resources.

**Comment by ARCHERS** [comment]
Great thanks for pointing me to the latest commit. I was using version 4.1.2 from Maven repository. Any idea of when the next version will be published to Maven?

**Comment by aetasoul** [comment]
When the milestone v4.2 is completed we will release the version. You can follow the progress from: https://github.com/stefanuebe/vaadin_fullcalendar/milestone/5

**Comment by stefanuebe** [comment]
Released with 4.1.3.
