### ISSUE TITLE
Guess: Fullcalendar 4.1.2 is incompatible with vaadin-bom 23.0.1

### ISSUE THREAD

**Issue by YChen9511** [stefanuebe/vaadin_fullcalendar#151]
Hi team,

When I applied fullcalendar 4.1.2, an error occured as shown below.
<img width="514" alt="截屏2022-06-08 下午6 04 15" src="https://user-images.githubusercontent.com/52761676/172593248-d5a611ec-2164-4175-9977-036c741771d5.png">

Then I opened FlowClient.js, but I didn't find any function called setOption. I guess it is caused by incompatible vaadin-bom version. If not, do you know the cause?

Here is my code:
```
@PageTitle("name1")
@Route(value="name1", layout=MainLayout.class)
public class CalendarLayout extends VerticalLayout {
       public CalendarLayout() {
              add(FullCalendarBuilder.create().build());
       }
}
```

Regards

**Comment by stefanuebe** [comment]
Hi, I'll check it tomorrow and see, if a fix is necessary

**Comment by aetasoul** [comment]
Hi,
sorry but I can't look at this. I'll be in mexico untill the end of July

**Comment by YChen9511** [comment]
> Hi, I'll check it tomorrow and see, if a fix is necessary

Beside, here are some info about my local env.

```
Java version: 11
springboot version: 2.5.4
vaadin framework: 23.0.1
chrome version: 102.0.5005.63(Official Build)(64-bit)
```

Thanks.

**Comment by YChen9511** [comment]
> Hi, sorry but I can't look at this. I'll be in mexico untill the end of July

It doesn't matter. Thanks for your reply.

**Comment by stefanuebe** [comment]
I can reproduce the issue in some way in 23.1.0. What was the reason at your system?

**Comment by stefanuebe** [comment]
In my case it was the whitelist in the application properties. Extending it with the proper package solved the issue. I will add that issue to the Wiki FAQ.

**Comment by stefanuebe** [comment]
Webapps application.properties 
```
vaadin.whitelisted-packages=other.packages.whatsoever,org.vaadin.stefan
```

**Comment by YChen9511** [comment]
> Webapps application.properties
> 
> ```
> vaadin.whitelisted-packages=other.packages.whatsoever,org.vaadin.stefan
> ```

The same reason as you. Thanks for your time.
