### ISSUE TITLE
security vulnerabilities : moment-Package

### ISSUE THREAD

**Issue by jverein** [stefanuebe/vaadin_fullcalendar#153]
Github Dependabot reports the following security vulnerabilites:

[Inefficient Regular Expression Complexity in moment ] [High] • Detected in moment (npm) • package-lock.json

[Path Traversal: 'dir/../../filename' in moment.locale ] [High] • Detected in moment (npm) • package-lock.json

[Cleartext Transmission of Sensitive Information in moment-timezone ] [Moderate]  • Detected in moment-timezone (npm) • package-lock.json

[Command Injection in moment-timezone ] [Low] • Detected in moment-timezone (npm) • package-lock.json

Please update to newer Versions

**Comment by stefanuebe** [comment]
Released with 4.1.3.
