### ISSUE TITLE
stickyHeaderDates: invisible horizontal scrollbar at top of resource timeline

### ISSUE THREAD

**Issue by aetasoul** [stefanuebe/vaadin_fullcalendar#155]
### Bug Description

By default the calendar use the `stickyHeaderDates` to `true`.
To workaround the problem just use `stickyHeaderDates`.

### Example Code

https://github.com/fullcalendar/fullcalendar/issues/6969

**Comment by aetasoul** [comment]
The same as https://github.com/fullcalendar/fullcalendar/issues/6973

**Comment by aetasoul** [comment]
I can take a screen of my application if needed but it's similar.

The problem appear on the resource based views, when clicking on the top event the view scroll left/right because of this

**Comment by aetasoul** [comment]
![test](https://user-images.githubusercontent.com/15131692/191428702-a6ee1608-d780-4ff6-980d-87a71157c0d5.gif)

**Comment by stefanuebe** [comment]
Didn't went to deep into this due to short time, but applying an additional overlfow-x plus removing the margin seemed to work:

![image](https://user-images.githubusercontent.com/36725474/192445428-5e2dd8ae-b97b-47a5-b1dc-ffaf688ac4f9.png)

**Comment by stefanuebe** [comment]
Applying the css via JS would be something like this:
`this.addCustomStyles('th[role="presentation"] div.fc-scroller-harness div.fc-scroller {overflow-x: hidden !important; margin-bottom: unset !important;}')`, where `this` is the current full-calendar instance. In Java it could be set in the same way using the custom styles method (but the quotes have to be replaced ofc :) ).

Potential workaround / fix for now, @aetasoul ?

**Comment by stefanuebe** [comment]
Ok, just saw, that in the other issue someone posted exactly this as a potential solution :D so ignore my previous post regarding "I found a workaround" and replace it with "I integrated the fix from that one guy in the other issue"

**Comment by aetasoul** [comment]
Thank's for the fix :)
