### ISSUE TITLE
eventResize / scheduler delta is undefined when resize from begining ( left ) of event

### ISSUE THREAD

**Issue by sonnessa** [stefanuebe/vaadin_fullcalendar#16]
I used the full calendar schedule with the following versions:
fullcalendar-scheduler: 1.3.0
fullcalendar: 1.8.0

I face the same issue fixed here:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/416

Which version of javascript component is using the 1.3.0 version?

Thanks in advance,
Michele

**Comment by stefanuebe** [comment]
It's currently using 3.9.0. Will update the version in the next days to 3.10.0, which should fix this problem.

**Comment by stefanuebe** [comment]
Next release version 1.9.0 will contain the newest FC 3 version, that should fix the problem.

 Will be uploaded today.
