### ISSUE TITLE
Unable to start app with version 6 and Vaadin 24.0.5

### ISSUE THREAD

**Issue by simasch** [stefanuebe/vaadin_fullcalendar#170]
I've updated to version 6.0.0 and get this error when starting in dev mode:

2023-05-30 08:38:00.355 ERROR 44640 --- [onPool-worker-1] c.v.f.s.frontend.TaskRunDevBundleBuild   :     : Command `C:\Program Files\nodejs\node.exe C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\node_modules\vite\bin\vite.js build` failed:
vite v4.1.3 building for production...
transforming...
✓ 341 modules transformed.
[vite:load-fallback] Could not load C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\frontend\generated\jar-resources/full-calendar-scheduler.js (imported by frontend/generated/jar-resources/full-calendar-with-tooltip.js): ENOENT: no such file or directory, open 'C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\frontend\generated\jar-resources\full-calendar-scheduler.js'
error during build:
Error: Could not load C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\frontend\generated\jar-resources/full-calendar-scheduler.js (imported by frontend/generated/jar-resources/full-calendar-with-tooltip.js): ENOENT: no such file or directory, open 'C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\frontend\generated\jar-resources\full-calendar-scheduler.js'

**Comment by stefanuebe** [comment]
Using the default starter app from start.vaadin.com, integrating the 6.0.0 with a simple sample worked. Same for the demo. 

Can you give me any additional details regarding your project / use case?

**Comment by simasch** [comment]
Did you try with full-calendar-scheduler?

Because that's what it complains about.

**Comment by stefanuebe** [comment]
Yep.

![image](https://github.com/stefanuebe/vaadin_fullcalendar/assets/36725474/67ee7f4a-507d-4bd4-85bc-2b10a03d9d5b)

```java
public HelloWorldView() {
    FullCalendar calendar = FullCalendarBuilder.create().withScheduler(Scheduler.GPL_V3_LICENSE_KEY).build();

    var provider = calendar.getEntryProvider().asInMemory();
    Entry entry = new Entry();
    entry.setStart(LocalDate.now());
    entry.setEnd(LocalDate.now());
    entry.setTitle("Hello World");
    provider.addEntry(entry);
    provider.refreshAll();

    setDefaultHorizontalComponentAlignment(Alignment.STRETCH);
    addAndExpand(calendar);
}
```

**Comment by stefanuebe** [comment]
Do you have any other details, that may help reproducing the issue?

**Comment by simasch** [comment]
I cleaned everything and now I get

> [vite:load-fallback] Could not load C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\frontend\generated\jar-resources/full-calendar-scheduler.js (imported by frontend/generated/jar-resources/full-calendar-with-tooltip.js): ENOENT: no such file or directory, open 'C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\frontend\generated\jar-resources\full-calendar-scheduler.js'
> error during build:
> Error: Could not load C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\frontend\generated\jar-resources/full-calendar-scheduler.js (imported by frontend/generated/jar-resources/full-calendar-with-tooltip.js): ENOENT: no such file or directory, open 'C:\Users\simon\Workspace\Dynasoft\tosca-ui\tosca-develop\frontend\generated\jar-resources\full-calendar-scheduler.js'

And this is correct because the full-calender-scheduler.js is in the directory vaadin-full-calendar

**Comment by simasch** [comment]
I didn't remember that we indeed did a subclass. Now everything works.

Thanks a lot for your help.

**Comment by stefanuebe** [comment]
You're welcome :)
