### ISSUE TITLE
assigning rerenderDelay?

### ISSUE THREAD

**Issue by corbettcode** [stefanuebe/vaadin_fullcalendar#18]
I'm setting up the scheduler as follows:

scheduler.setSchedulerLicenseKey( Scheduler.GPL_V3_LICENSE_KEY );
scheduler.changeView( SchedulerView.TIMELINE_WEEK );
scheduler.setOption( MIN_TIME, "06:00:00" );
scheduler.setOption( MAX_TIME, "19:00:00" );
scheduler.setOption( SLOT_DURATION, "00:15:00" );
scheduler.setOption( WEEKENDS, false );
scheduler.setNowIndicatorShown( true );

scheduler.addViewRenderedListener( estimatorsTimelinePresenter::handleViewRenderedEvent );

This seems to cause the ViewRenderedEvent to be fired multiple times in rapid succession:

19:42:06.703 [http-nio-8080-exec-9] | INFO  | c.c.u.v.t.EstimatorsTimelinePresenter    |   | View rendered: [2019-06-30][2019-08-11]
19:42:06.703 [http-nio-8080-exec-9] | INFO  | c.c.u.v.t.EstimatorsTimelinePresenter    |   | View rendered: [2019-06-30][2019-08-11]
19:42:06.703 [http-nio-8080-exec-9] | INFO  | c.c.u.v.t.EstimatorsTimelinePresenter    |   | View rendered: [2019-07-07][2019-07-14]
19:42:06.703 [http-nio-8080-exec-9] | INFO  | c.c.u.v.t.EstimatorsTimelinePresenter    |   | View rendered: [2019-07-07][2019-07-14]
19:42:06.704 [http-nio-8080-exec-9] | INFO  | c.c.u.v.t.EstimatorsTimelinePresenter    |   | View rendered: [2019-07-07][2019-07-14]
19:42:06.704 [http-nio-8080-exec-9] | INFO  | c.c.u.v.t.EstimatorsTimelinePresenter    |   | View rendered: [2019-07-07][2019-07-14]
19:42:06.704 [http-nio-8080-exec-9] | INFO  | c.c.u.v.t.EstimatorsTimelinePresenter    |   | View rendered: [2019-07-08][2019-07-13]
19:42:06.704 [http-nio-8080-exec-9] | INFO  | c.c.u.v.t.EstimatorsTimelinePresenter    |   | View rendered: [2019-07-08][2019-07-13]

Seems like being able to set the rerenderDelay would prevent this from happening. In the current version, can the rerenderDelay be assigned? If so, how would that be accomplished?

**Comment by stefanuebe** [comment]
Hey there, I know, that V4 of the FC has this delay option, but I didn't found it for V3 (which the addon is currently based on). When it is a normal option in V3, you could set it as with other options (using the string key version of the method), but nor sure, if it is yet supported there.

**Comment by corbettcode** [comment]
Okay, thanks

**Comment by istibekesi** [comment]
How/when to load entries to the calendar then? 
ViewRenderedEvent callback seemed to be the right way to to it, but this way it fetches the data multiple times on init.
