### ISSUE TITLE
License

### ISSUE THREAD

**Issue by naydennn** [stefanuebe/vaadin_fullcalendar#180]
Hello, 
Can I use this this full calendar with scheduler with those license? What is the differences between those license and which one should I use? Is it free or not?

**Comment by stefanuebe** [comment]
We do NOT provide any license for the scheduler itself. The scheduler library is a commercial / paid addon for the FC. We just provide the Vaadin Flow integration, which does not affect the necessary licenses for the Scheduler library, that runs in the background. 

So the answers to your questions are: no, the scheduler is not free, only our integration for Vaadin Flow is (under the MIT license). You need to buy a proper license from https://fullcalendar.io/, which you then can setup via the Java API to make the addon full functional. The MIT license of this addon covers only our integration code (the code in this repository).

Please also see this wiki entry for infos regarding the licenses: https://github.com/stefanuebe/vaadin_fullcalendar/wiki/FullCalendar-Scheduler-License

I hope this helps.
