### ISSUE TITLE
Setting business hours to SUNDAY

### ISSUE THREAD

**Issue by Nedzadp** [stefanuebe/vaadin_fullcalendar#19]
Hi Stefan,
I tried to set business hours to Sunday, but it seems like it doesn't work. I checked the documentation https://fullcalendar.io/docs/businessHours and it uses zero-based day of week integers (0=Sunday). BusinessHours uses DayOfWeek enum where value follows the ISO-8601 standard, from 1 (Monday) to 7 (Sunday). 
I can probably override toJson and check if Sunday pass 0 ? Do you have any suggestions ?
Thank you.

**Comment by stefanuebe** [comment]
Updated the toJson method, it will map SUNDAY to 0.
