### ISSUE TITLE
Functionality scheduler

### ISSUE THREAD

**Issue by Sergio70** [stefanuebe/vaadin_fullcalendar#2]
Hi good day
You have done a great job :), you will have plans to add the functionality of ("scheduler") because it would be great since this is very requested?

https://fullcalendar.io/scheduler

**Comment by stefanuebe** [comment]
Hi, thanks for the feedback. Currently I don't have plans for that, but does not mean that I won't do anything in that direction in near future :)

**Comment by stefanuebe** [comment]
You may have a look at the branch "scheduler", there is now some developing ongoing. Don't know when it will be released, hope in the next days with a first set of features.

**Comment by Sergio70** [comment]
woo! this is fabulous, this project is great ..
Thanks for this functionality!
