### ISSUE TITLE
using scheduler - (TypeError) : $0.removeResource is not a function

### ISSUE THREAD

**Issue by corbettcode** [stefanuebe/vaadin_fullcalendar#20]
Using version 1.3.1, when calling the method FullCalendarScheduler.removeAllResources(), the above error is presented on the web site screen. In reviewing full-calendar-scheduler.html a function with the name 'removeResource' was not found.

If I am doing something wrong, please advise.

**Comment by stefanuebe** [comment]
Yes, thats indeed an deprecation error. Will be fixed in 1.3.2

**Comment by stefanuebe** [comment]
I just saw, that I forgot to update the version in the directory, sorry for that. Is now up to date with RC2.
