### ISSUE TITLE
Version for Vaadin 14 (NPM)

### ISSUE THREAD

**Issue by markusherr** [stefanuebe/vaadin_fullcalendar#21]
Since Vaadin 14 has moved from bower / HTML imports / Polymer 2 to NPM, JavaScript Modules and Polymer 3, this addon should also be migrated to Vaadin 14 with NPM mode. Bower mode is now deprecated.

**Comment by stefanuebe** [comment]
Is currently WIP, you can find the latest version (currently alpha) here: https://vaadin.com/directory/component/full-calendar-4-web-component
