### ISSUE TITLE
Month view is displaying too many weeks

### ISSUE THREAD

**Issue by bdauvissat** [stefanuebe/vaadin_fullcalendar#23]
Hi
When I display January 2020, we can see that 6 weeks are displayed.
But week 6 is only February.
Is there a way to remove it ?
It also happens sometime at the beginning of the month.
By the way, your calendar is very usefull.
Regards

![weeks](https://user-images.githubusercontent.com/2834352/66113161-8b9e3080-e5cc-11e9-8706-bd012811c76e.png)

**Comment by stefanuebe** [comment]
I'll check it these days, but my gut tells me, that this might be a FC library problem. Have you checked their github issues?

**Comment by bdauvissat** [comment]
Hi.
Thanks for your answer.
Sorry but I don't know FC.
So no, I didn't check their github.

**Comment by stefanuebe** [comment]
Ok, I'll see, if I find the issue, but might take some days.

**Comment by bdauvissat** [comment]
This is not an emergency :)
Thanks for your work, it helped me a lot.

**Comment by stefanuebe** [comment]
Seems to be an issue of the internally used JS library. I created an issue in their github and will integrate the fix version as soon as there is one.

https://github.com/fullcalendar/fullcalendar/issues/5080

**Comment by bdauvissat** [comment]
Thanks a lot.

**Comment by stefanuebe** [comment]
So looks like its intentional, since most month span over 6 CW while some are 5 long. It needs a new feature to deactivate it.

**Comment by stefanuebe** [comment]
Hi. It seems that V4 now has an option to set the fixed week count. By default it is true and thus 6 weeks long. You can deactivate that by setting the option to false.

Here is the FCs page. Use the setOption(String, ...) to set the option in Java (haven't tried it myself yet).

https://fullcalendar.io/docs/v4/fixedWeekCount

**Comment by kamuffe** [comment]
Hi.

fixedWeekCount comes to rescue here. We tried it out and it works.

So it is configurable in FC. Issue can be closed.

Best,
Kamuffe

**Comment by aetasoul** [comment]
Hi, we have finally released the version 2.4.0 on the [Vaadin Directory](https://vaadin.com/directory/component/full-calendar-4-scheduler-web-component/overview)

Update your FC version and if you experience any other problem please report it :)
