### ISSUE TITLE
FullCalendarScheduler V14 - TypeError: Cannot read property 'id' of null 

### ISSUE THREAD

**Issue by LucaMurarolli** [stefanuebe/vaadin_fullcalendar#26]
Hi,
I'm making a very simple sample and I'm stuck with an error that says:
> TypeError: Cannot read property 'id' of null 
using addEntryDroppedListener method. 

This is my code:
`FullCalendarScheduler calendar = new FullCalendarScheduler();
calendar.setSchedulerLicenseKey(Scheduler.GPL_V3_LICENSE_KEY);
calendar.setTimeslotsSelectable(true);
calendar.setOption("resourceLabelText", "Sgusciatrici");
calendar.setOption("resourceAreaWidth", "10%");
calendar.setLocale(Locale.ITALY);
      
Resource sgusciatrice = new Resource("AAA", "prova", "green");
calendar.addResource(sgusciatrice);
ResourceEntry entry1 = new ResourceEntry("BBB", "ciao", LocalDateTime.now(), LocalDateTime.now().plusHours(1), false, true, "green", "descrizione");
entry1.setResource(calendar.getResourceById("AAA").get());
calendar.addEntry(entry1);
calendar.setLocale(Locale.ITALY);

calendar.addEntryDroppedListener(event -> {
	Notification notification2 = new Notification("Dropped");
	notification2.open();
});`

Vaadin version: 14.0.11

**Comment by LucaMurarolli** [comment]
One more hint... If i drag the entry in this way 
![image](https://user-images.githubusercontent.com/57721117/68874674-e82f5800-0701-11ea-8d89-6266ae79812f.png)
I have the error, but if i move in this way
![image](https://user-images.githubusercontent.com/57721117/68874770-07c68080-0702-11ea-94e6-5146b596ce67.png)
dropping with the cursor on the second line (the entry is dropped on the first line anyway) everything goes correctly,

**Comment by stefanuebe** [comment]
Will be fixed in next release (RC5 + RC3), published hopefully end of this day.
