### ISSUE TITLE
Hide day names in calendar

### ISSUE THREAD

**Issue by jayantarijal3** [stefanuebe/vaadin_fullcalendar#33]
- Need to hide the day names in the calendar like "Sunday", "Monday".

- Need the first letter of the day names in the calendar.

Is there any method for that?

**Comment by stefanuebe** [comment]
Hi, I'm currently in parental leave up to April, so I cannot say when I have time for a deeper look into your question.

**Comment by stefanuebe** [comment]
This is not doable via Java, I guess you'll have to achieve that by using css. 

The easiest way I assume would be to create a subclass of the calendar and insert your own custom css (for instance hide the day cells or use the content property, something like that).

Have a look in the samples on how to subclass the polymer class:

https://vaadin.com/directory/component/full-calendar-4-web-component/samples (last sample)
