### ISSUE TITLE
Is it possible to disable drag and drop for entries ?

### ISSUE THREAD

**Issue by bdauvissat** [stefanuebe/vaadin_fullcalendar#34]
Hi,
when using the Full Calendar, I noticed that entries can be dragged and dropped from a day to another.
Is there a way to disable this behaviour ?

Thanks a lot for your work.

PS : I'm using Vaadin 14 and the FullCalendar2 v 2.0.0.alpha2

**Comment by stefanuebe** [comment]
Hi, I'm currently in parental leave up to April, so I cannot say when I have time for a deeper look into your question.

**Comment by kamuffe** [comment]
@bdauvissat yes it is possible with the following API:

Entry basicEvent = new Entry(...);
basicEvent.setEditable( false );

That way the event is displayed but you cannot Drag&Drop it anymore.

Best,
Kamuffe
