### ISSUE TITLE
Not working in production mode

### ISSUE THREAD

**Issue by martinisraelsen** [stefanuebe/vaadin_fullcalendar#35]
The FullCalendar is not showing when the application is built in production mode. Attached is a sample program with the Vaadin spring starter (I did not try without spring).

The Calendar shows when running in development mode.

mvn spring-boot:run

But not when run in production mode.

mvn spring-boot:run -Pproduction

I did not see any errors on the server or in the browser console.

I did include @EnableVaadin.

[calendar-test.zip](https://github.com/stefanuebe/vaadin_fullcalendar/files/4067748/calendar-test.zip)

**Comment by stefanuebe** [comment]
Hi, I'm currently in parental leave up to April, so I cannot guarantee to have a look on this issue. Feel free to fix it, if needed and create pull request. For merging that and uploading a new version, I guess I'll find some time.

**Comment by martinisraelsen** [comment]
Hi Stefan, we’ll congratulations then!

I’m not a JS expert, but the issue is preventing me to move to NPM mode, so I’ll try to take a look at it and see if I can figure out what’s going on next week.

Thanks
Martin

**Comment by martinisraelsen** [comment]
Hello Stefan,

I did a little more digging with FullCalendar / V14 / Spring / Production Mode. 

Here’s what I’m seeing:

V14 + Spring + FullCalendar in development mode: Working
V14 + Spring + FullCalendar in production mode: Working

V14 + Spring + FullCalendar Scheduler in development mode: Working
V14 + Spring + FullCalendar Scheduler in production mode: Not Working

The FullCalendar scheduler in production mode is not working (but regular calendar is). The test app does have @EnableVaadin() and the component is included in the frontend html, but it’s blank. 

Screen shots for Development Mode:


Screenshot for production mode (-Pproduction)

**Comment by martinisraelsen** [comment]
<img width="684" alt="Screen Shot 2020-03-04 at 5 26 57 AM" src="https://user-images.githubusercontent.com/6271003/75870610-36638680-5dd9-11ea-95b9-b72b8b6f1759.png">

**Comment by martinisraelsen** [comment]
Hello Stefan,

Finally figured out the root cause of this. It's not a bug. The issue was that I didn't have an explicit reference to the FullCalendarScheduler.

I had
`
 FullCalendar calendar = FullCalendarBuilder.create().withScheduler().build();
`

Changing it to 

`
FullCalendarScheduler calendar = (FullCalendarScheduler) FullCalendarBuilder.create().withScheduler().build();
`

Fixed the issue.
