### ISSUE TITLE
applyChangesOnEntry executed on addEntryDroppedListener does not apply right resource

### ISSUE THREAD

**Issue by sonnessa** [stefanuebe/vaadin_fullcalendar#36]
Hi,
when I run  entry = e.applyChangesOnEntry(); in event listener addEntryDroppedListener
returned entry still contains the original (source) resource.

I don't know how to get the new resource of the dropped cell.

The same code worked with previous version (1.9.2 for vaadin 13).

Did anything change in apis?
Thanks for your help.

Regards,
Michele Sonnessa

**Comment by sonnessa** [comment]
Resolved in https://github.com/zero11it/vaadin_fullcalendar/tree/scheduler-draganddrop

**Comment by stefanuebe** [comment]
Is that his PR? https://github.com/stefanuebe/vaadin_fullcalendar/pull/38

**Comment by sonnessa** [comment]
Yes it is. Apply method was not aware of new resource, because it is provided by specific event parameters.
