### ISSUE TITLE
i18n not fully implemented

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#39]
Hi Stefan.

We experienced an issue with i18n.
When we change the locale e.g. to german, not all texts are translated as expected. 

fullCalendar.setLocale( Locale.ENGLISH );
![i18n_english](https://user-images.githubusercontent.com/5285367/75624654-9a5a3500-5bb6-11ea-9123-a7218d0255d2.PNG)

fullCalendar.setLocale( Locale.GERMAN );
![i18n_german](https://user-images.githubusercontent.com/5285367/75624657-9b8b6200-5bb6-11ea-8749-7f60f7e2f21c.PNG)
Note that "all-day" should be "Ganztägig" and "W9" should be "KW9"

Tested the demo at https://fullcalendar.io/#demos and there it is correct.
![i18n_german-fullcalendar-demo](https://user-images.githubusercontent.com/5285367/76289881-6cf24300-62aa-11ea-85f5-a9f147d2f72b.PNG)

Best,
Kamuffe

**Comment by stefanuebe** [comment]
Looks like the missing locale import is the reason for that. Strange, since most of the localization works anyways.

**Comment by stefanuebe** [comment]
Fixed in 2.1.1
