### ISSUE TITLE
FullCalendar not available when application is built in Productive mode

### ISSUE THREAD

**Issue by marty-buly** [stefanuebe/vaadin_fullcalendar#4]
Hi Stefan,

once I've built my application for production, FullCalendar is not showing anymore. I'm not really sure, what it is, but my observation is that your structure of static files (like full-calendar.html, fullcalendar.min.js, ...) is not the same as for other vaadin web components.
E.g. vaadin-grid has structure of META-INF/resources/webjars/vaading-grid (similarly all other vaadin components). Your project has structure like META-INF/resources/frontend/bower_components/fullcalendar.

Could you please check and generate jar file, which is consistent with other webjars? 
Thnx
Martin

**Comment by stefanuebe** [comment]
Fixed in version 1.3.1 (FC) / 1.0.1 (Sched).
