### ISSUE TITLE
Build error "Can't resolve 'moment-timezone/builds/moment-timezone-with-data?babel-target=es5'"

### ISSUE THREAD

**Issue by fschon** [stefanuebe/vaadin_fullcalendar#42]
FullCalendar4 v2.1.0
After having a stable build for some time, I deleted the node_modules directory and on webpack rebuild the below error occurs. The pom.xml contains the build-frontend goal as follows:

            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-frontend</goal>
                            <goal>build-frontend</goal> 
                        </goals>
                    </execution>
                </executions>
            </plugin>

Error trace:

> ERROR in ../node_modules/@fullcalendar/moment-timezone/main.esm.js?babel-target=es5
Module not found: Error: Can't resolve 'moment-timezone/builds/moment-timezone-with-data?babel-target=es5' in 'G:\proj\newco\embedded\node_modules\@fullcalendar\moment-timezone'
 @ ../node_modules/@fullcalendar/moment-timezone/main.esm.js?babel-target=es5 7:0-58
 @ ../node_modules/@vaadin/flow-frontend/full-calendar.js?babel-target=es5
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5

> ERROR in ../node_modules/@fullcalendar/moment-timezone/main.esm.js?babel-target=es6
Module not found: Error: Can't resolve 'moment-timezone/builds/moment-timezone-with-data?babel-target=es6' in 'G:\proj\newco\embedded\node_modules\@fullcalendar\moment-timezone'
 @ ../node_modules/@fullcalendar/moment-timezone/main.esm.js?babel-target=es6 7:0-58
 @ ../node_modules/@vaadin/flow-frontend/full-calendar.js?babel-target=es6
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6

Have some versions changed and dependencies no longer found?

Thanks for checking.

**Comment by stefanuebe** [comment]
Cannot reproduce the problem. Removed node modules, also package.json and built the demo with production mode (so that frontend dependencies are directly resolved). Build was successful. 

Can you share your pom file please?

**Comment by fschon** [comment]
I think there was an issue with the files in the repositories. To get past the initial problem I manually npm installed the moment-timezone package and it all worked. Then some days/weeks later I deleted all the files again and did a rebuild and the build works fine again. Since I changed nothing else on my side I am guessing that there was a bad package in the repo.
