### ISSUE TITLE
Layout destroyed after F5 (Vaadin 15)

### ISSUE THREAD

**Issue by marcelhallmann53** [stefanuebe/vaadin_fullcalendar#44]
Hi,

I just upgraded to Vaadin version 15.0.4, but now the calendar component behaves strange after refreshing the browser:
First the calender is displayed correctly:
![image](https://user-images.githubusercontent.com/63244906/79065386-35fbbc80-7cb0-11ea-8ace-f6c1c87e6014.png)

After hitting F5 the whole layout is destroyed:
![image](https://user-images.githubusercontent.com/63244906/79065399-47dd5f80-7cb0-11ea-9ccc-2a420bad33a0.png)

**Comment by stefanuebe** [comment]
Can you please share the source code of the class, that embeds the calendar?

**Comment by marcelhallmann53** [comment]
Yes, of course (stripped version):
`@Route(value = CalendarView.ROUTE, layout = MainView.class)
@PageTitle(NAVIGATION_CAPTION)
public class CalendarView extends VerticalLayout implements AfterNavigationObserver {

    static final String ROUTE = "meeting";
    public static final String NAVIGATION_CAPTION = "Calendar";

    private final ClientService clientService;
    private final MeetingService meetingService;

    private FullCalendar calendar;

    @Autowired
    public CalendarView(ClientService clientService, MeetingService meetingService) {
        this.clientService = clientService;
        this.meetingService = meetingService;
    }

    @PostConstruct
    void configureComponents() {
        setHeightFull();

        calendar = createCalendar();
        add(calendar);
        setFlexGrow(1, calendar);
    }
    private FullCalendar createCalendar() {
        FullCalendar calendar = FullCalendarBuilder.create().build();
        calendar.setBusinessHours(
                new BusinessHours(of(7, 0), of(20, 0), DEFAULT_BUSINESS_WEEK),
                new BusinessHours(of(7, 0), of(20, 0), SATURDAY));
        calendar.setLocale(Locale.GERMAN);
        calendar.setFirstDay(MONDAY);
        calendar.setSnapDuration("03:00");
        calendar.setNowIndicatorShown(true);
        calendar.setMinTime(of(7, 0));
        calendar.setMaxTime(of(20, 0));
        calendar.changeView(TIME_GRID_WEEK);

        return calendar;
    }
}
`

**Comment by stefanuebe** [comment]
Ok, I will check that, but cannot promise a fast result. I could not reproduce it in V14 so it might be related to some changes that came up with V15.

**Comment by stefanuebe** [comment]
As a workaround you could try setting the calendar height to auto (by default it is parent). 

`calendar.setHeightAuto();`. 

This is a client side option that lets the calendar calculate the needed height. Alternatively you could set the height to a fixed size using `calendar.setHeight(500)` (the int parameter version).

I also had some severe JS issues using V15. Not sure, if the addon works out of the box with V15.

**Comment by stefanuebe** [comment]
I just also found out, that you have to set the calendar's height BEFORE changing the view. Otherwise it will destroy the calendar objects. Don't ask me why, needs to be investigated.

**Comment by marcelhallmann53** [comment]
> Ok, I will check that, but cannot promise a fast result. I could not reproduce it in V14 so it might be related to some changes that came up with V15.

I can confirm that everything works fine with V14, I tested with V14.1.23.

**Comment by marcelhallmann53** [comment]
> As a workaround you could try setting the calendar height to auto (by default it is parent).
> 
> `calendar.setHeightAuto();`.
> 
> This is a client side option that lets the calendar calculate the needed height. Alternatively you could set the height to a fixed size using `calendar.setHeight(500)` (the int parameter version).

I'll try and give you feedback, probably tomorrow afternoon

**Comment by stefanuebe** [comment]
also see https://github.com/stefanuebe/vaadin_fullcalendar/issues/45 about the mentioned order.

**Comment by marcelhallmann53** [comment]
Hi Stefan,

I had a little time to do some tests using the `calendar.setHeightAuto();` you mentioned.
It seems to enforce the correct calculation of the calendar's height, but the entries are broken as well as the width of the first column and the "current time marker" (the little red arrow):

Initial:
![image](https://user-images.githubusercontent.com/63244906/79686317-c6517880-823f-11ea-8583-1a7870f3474d.png)

After F5:
![image](https://user-images.githubusercontent.com/63244906/79686328-dc5f3900-823f-11ea-875f-76120e465e0d.png)

I tried
````
        calendar.setHeightAuto();
        calendar.changeView(TIME_GRID_WEEK);

        return calendar;
````
as well as
````
        calendar.changeView(TIME_GRID_WEEK);
        calendar.setHeightAuto();

        return calendar;
````

Using `calendar.setHeight(500)` didn't make a difference.

**Comment by stefanuebe** [comment]
Guess I found the issue, at least with the initial false size. It seems, that there have been changes regarding some rendering lifecycles with V15 (not sure if that is a bug or wandet change), which has the result, that the calendar cannot obtain the container's height, since it is simply not rendered and thus not available yet. 

A fix for that is to add an after rendered event listener, that updates the size. I will provide a fix for that.

**Comment by stefanuebe** [comment]
See 2.2.3
