### ISSUE TITLE
Calendar broken when set business hours inside TimeslotsSelectedListener

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#49]
Hi Stefan.

I found an issue that the calendar gets broken when adding the following TimeslotsSelectedListener

```
calendar.addTimeslotsSelectedListener(c -> {

	List<BusinessHours> businessHours = new ArrayList<>();

	LocalDateTime now = LocalDateTime.now();
	BusinessHours bh = new BusinessHours(now.toLocalTime(), now.plusHours(1).toLocalTime(), now.getDayOfWeek());
	businessHours.add(bh);

	// FIXME these two lines break the calender when selecting time ranges
	calendar.removeBusinessHours();
	calendar.setBusinessHours(businessHours.toArray(new BusinessHours[businessHours.size()]));
});
```

The calendar gets broken only if inside this listener the business hours are set. If these two lines are commented out the calender works as expected. But setting the business hours is exactly what we want to do.

I added the code above with your the latest FullCalender Demo.
I tested a bit around but cannot find any solution.

![CalendarError](https://user-images.githubusercontent.com/5285367/80277389-d8736100-86ee-11ea-9f56-25cce883239b.gif)

Best,
Kamuffe

**Comment by stefanuebe** [comment]
It might be a general problem to set options inside there. Tested it with calendar.setLocale(...), also broke it.

**Comment by stefanuebe** [comment]
Might be related to this https://github.com/fullcalendar/fullcalendar/issues/5270 and this https://github.com/fullcalendar/fullcalendar/issues/5266

**Comment by kamuffe** [comment]
Thanks Stefan for your investigation. 

Sadly we have to wait :(

**Comment by kamuffe** [comment]
@stefanuebe I created a PR updating FC which fixes the issue.
Best,
Kamuffe

**Comment by kamuffe** [comment]
Fix working, closing issue.
