### ISSUE TITLE
Adding an entry to the calendar does nothing

### ISSUE THREAD

**Issue by bsheely** [stefanuebe/vaadin_fullcalendar#50]
` private void loadCalendar() {
        List<LocalDate> dateRange = selectedCycle == CURRENT ? ScheduleUtility.getCurrentCycleDateRange(selectedSchedule) : ScheduleUtility.getNextCycleDateRange(selectedSchedule);
        List<CalendarEntry> calendarEntries = calendarEntryService.findAllByScheduleAndDateBetweenExclusive(selectedSchedule, dateRange.get(0).minusDays(1), dateRange.get(1).plusDays(1));
        Collections.sort(calendarEntries);
        for (CalendarEntry calendarEntry : calendarEntries) {
            System.out.println(calendarEntry.getModality().name());
            if (!calendarEntry.getModality().name().equals("OFF"))
                System.out.println(StringUtil.ConvertStringListToString(calendarEntry.getWodDescription()));
            System.out.println("\n");
            Entry entry = new Entry();
            entry.setTitle(calendarEntry.getModality().name());
            if (!calendarEntry.getModality().name().equals("OFF"))
          entry.setDescription(StringUtil.ConvertStringListToString(calendarEntry.getWodDescription()));
            entry.setColor(calendarEntry.getModality() != OFF ? "black" : "gray");
            entry.setAllDay(true);
            calendar.addEntry(entry);
        }
        //calendar.render();
    }`

My code to load the calendar was taken from your code examples. The calendar is still blank after this method is called.

**Comment by stefanuebe** [comment]
First of all: Can you please post issue code in a more readable way? It spares some time when I don't have to post it to my IDE first to read it (you can post code as a code block by wrapping it into triple ` signs, see result below). Thanks 🙂 

To the issue: You do not set dates to the entry, thus the calendar cannot display them correctly (as it simply does not know where to place them). You have to provide at least a start date. 

```
    private void loadCalendar() {
        List<LocalDate> dateRange = selectedCycle == CURRENT ? ScheduleUtility.getCurrentCycleDateRange(selectedSchedule) : ScheduleUtility.getNextCycleDateRange(selectedSchedule);
        List<CalendarEntry> calendarEntries = calendarEntryService.findAllByScheduleAndDateBetweenExclusive(selectedSchedule, dateRange.get(0).minusDays(1), dateRange.get(1).plusDays(1));
        Collections.sort(calendarEntries);
        for (CalendarEntry calendarEntry : calendarEntries) {
            System.out.println(calendarEntry.getModality().name());
            if (!calendarEntry.getModality().name().equals("OFF"))
                System.out.println(StringUtil.ConvertStringListToString(calendarEntry.getWodDescription()));
            System.out.println("\n");
            Entry entry = new Entry();
            entry.setTitle(calendarEntry.getModality().name());
            if (!calendarEntry.getModality().name().equals("OFF"))
                entry.setDescription(StringUtil.ConvertStringListToString(calendarEntry.getWodDescription()));
            entry.setColor(calendarEntry.getModality() != OFF ? "black" : "gray");
            entry.setAllDay(true);
            calendar.addEntry(entry);
        } //calendar.render(); }
    }
```
