### ISSUE TITLE
vaddin 14.1.25 and 14.1.27 .js issue 

### ISSUE THREAD

**Issue by hdimov** [stefanuebe/vaadin_fullcalendar#52]
Dear Stefan, 

Still having problems when using component with specified vaadin versions. Even after usage of build-frontend goad, still having the following error in browser:

TypeError: $0.$connector is undefined 

Regards,

**Comment by jcgueriaud1** [comment]
As a workaround, you can add @NpmPackage(value = "moment", version = "2.24.0") on the route where you are using the calendar or on the main Route Layout.
This will use the exact version of moment (the add-on uses ^2.24.0 and 2.25.x seems broken and was upgraded 3 days ago).

Here the error: 
https://github.com/nasa/openmct/issues/2999

**Comment by jcgueriaud1** [comment]
You also need to clean package-lock and target folder.
The other problem is that there is priority for the annotations (the workaround annotation and the component annotation). So it may not solve the problem.

Hopefully it will be solve by updating the add-on.

**Comment by hdimov** [comment]
10x for the fix :)
Confirmed working state of vaadin_fullcalendar for both versions.
For now moment <= 2.24.0 when using calendar, fixed with @NpmPackage - i.e. annotation worked (overtakes the component annotation)
Also tried, w/o build-frontend goal - component looks fine in browser :)

**Comment by stefanuebe** [comment]
Hey guys, thanks for the feedback. I'll try to integrate the correct version these days.

**Comment by stefanuebe** [comment]
Fixed in 2.2.4.
