### ISSUE TITLE
Event tooltip

### ISSUE THREAD

**Issue by aetasoul** [stefanuebe/vaadin_fullcalendar#56]
Hi Stefan,
There is a way to add the Tooltip to the Entrys?

Is possible to implement the tooltip like [here](https://fullcalendar.io/docs/event-tooltip-demo)?

Actually my code is:

1.  Get resources and entrys from the DB
1.  Elaborate resource and entrys 
1.  Add resources and entrys to the calendar
1.  setting the entryrendercallback

`calendar.setEntryRenderCallback("function(info){ var tooltip = new Tooltip(info.e1, { title: info.event.extendedProps.description, placement: 'top', trigger: 'hover', container: 'body' }); }");`

The problem is that Tooltip library is not found during page loading, I don't know how to install in my project (or your project), or if there is an alternative solution.

Thanks
Best Regards

**Comment by stefanuebe** [comment]
Depending on the tooltip library you have to add the npm declaration to your Java class, that uses the FullCalendar (or you extend the FullCalendar and add it to this subclass), by using the @NpmPackage annotation. After a rebuild of your application it should include these packages to your app and you can use them on the client side.

So for instance when you want to use the tippy.js library, it would be something like `@NpmPackage(name = "tippy.js", version="6.2.3")` (or similar) plus potentially needed other npm packages (popper js in this case).

**Comment by aetasoul** [comment]
For exaple like this?

``` java
import org.vaadin.stefan.fullcalendar.FullCalendarScheduler;

import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.dependency.NpmPackage;

@Tag("my-full-timeline")
@JsModule("./full-calendar-scheduler.js")
@JsModule("./my-full-timeline.js")
@NpmPackage(value = "tooltip.js", version = "1.6.1")
@NpmPackage(value = "popper.js", version = "1.0.1")
public class MyFullTimeline extends FullCalendarScheduler {
   
	private static final long serialVersionUID = 1L;

	public MyFullTimeline(int entryLimit) {
        super(entryLimit);
    }
}
```

I have checked here the versions:
1.  [Tooltip.js](https://www.npmjs.com/package/tooltip)
1.  [popper.js](https://www.npmjs.com/package/popper)

Running the rebuild I recive this error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for tooltip.js@1.6.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'zerp'
npm ERR! notarget 
```

So I checked with npm (`npm view tooltip`):

```
tooltip@1.6.1 | MIT | deps: 8 | versions: 12
Tooltip manager
https://github.com/radubrehar/tooltip

keywords: tooltip

dist
.tarball: https://registry.npmjs.org/tooltip/-/tooltip-1.6.1.tgz
.shasum: abc2b4bbab3f0859865ea325098b1262a8733d7d

dependencies:
clone: ^1.0.2                  matches-selector: ^1.0.0       region-align: ^2.1.2
contains: 0.1.1                object-assign: ^3.0.0          to-style: ^1.3.3
escape-html: ^1.0.2            react-style-normalizer: ^1.2.8

maintainers:
- zippyui <contact@zippyui.com>

dist-tags:
latest: 1.6.1

published over a year ago by zippyui <contact@zippyui.com>
```

**Comment by stefanuebe** [comment]
This version is far outdated, check https://atomiks.github.io/tippyjs/v5/getting-started/ and https://www.npmjs.com/package/tippy.js instead.

**Comment by aetasoul** [comment]
It works with Tippy, I have just replace tooltip and popper with `@NpmPackage(value = "tippy.js", version = "6.2.3")`

Just the last question, this is the right way to call the tooltip?

`calendar.setEntryRenderCallback("function(info) { new Tippy('tooltip', { position:'top', interactive:'true', animation:'perspective', arrow:'true', });) }");`

**Comment by aetasoul** [comment]
Ok, done it.

NpmPackage:
``` java
@NpmPackage(value = "@popperjs/core", version="2.4.0")
@NpmPackage(value = "tippy.js", version = "6.2.3")
```

Code:
``` java
	public void addTooltips() {
		setEntryRenderCallback("" 
				+ "function(info) { "
				+ "		const instance = tippy(info.el); "
				+ "		instance.setContent(info.event.title);"
				+ "		instance.setProps({"
				+ "			position:'top', "
				+ "			interactive:true, "
				+ "			animation:'perspective', "
				+ "			arrow:true, "
				+ "			followCursor:'horizontal', "
				+ "			theme:'translucent' "
				+ "			}); "
				+ "		}"
				);
	}
```

The only problem now is that the tooltip is not styled. I have imported the stylesheet:

```
@StyleSheet(value = "https://unpkg.com/tippy.js@6.2.3/animations/perspective.css")
@StyleSheet(value = "https://unpkg.com/tippy.js@6.2.3/themes/translucent.css")
```

**Comment by aetasoul** [comment]
It seems impossibile to implement the tippy library directly into the javascript of fullcalendar, so I decided to keep it in my class.

**Comment by stefanuebe** [comment]
Hven't tried it myself yet, but thought of bringing it maybe as an additional feature for the fc somewhere in the future

**Comment by aetasoul** [comment]
It is a nice feature to add, and is necessary on some calendar views I think. When you create a single day event and the descrition is very big, and you don't want to place on multi line

**Comment by stefanuebe** [comment]
Had you have other annotations, too? I tried it, too, but got "tippy not defined"

**Comment by aetasoul** [comment]
I also got: "tippy not defined". 
The only way to use it was to create a new class, where I import all the npm and JS module, after that I create a function that call your `EntryRenderCallback`:

``` java
import org.vaadin.stefan.fullcalendar.FullCalendarScheduler;

import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.CssImport;
import com.vaadin.flow.component.dependency.JavaScript;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.dependency.NpmPackage;
import com.vaadin.flow.component.dependency.StyleSheet;

import elemental.json.Json;
import elemental.json.JsonObject;

@NpmPackage(value = "@popperjs/core", version="2.4.0")
@NpmPackage(value = "tippy.js", version = "6.2.3")
@JsModule("./full-calendar-scheduler.js")
@JsModule("./my-full-timeline.js")
@CssImport(value = "tippy.js/dist/tippy.css")
@StyleSheet(value = "https://unpkg.com/tippy.js@6.2.3/animations/perspective.css")
@StyleSheet(value = "https://unpkg.com/tippy.js@6.2.3/themes/translucent.css")
@CssImport(value = "tippy.js/animations/perspective.css")
@CssImport(value = "tippy.js/themes/translucent.css")
@JavaScript(value = "https://unpkg.com/@popperjs/core@2.4.0")
@JavaScript(value = "https://unpkg.com/tippy.js@6.2.3")
@Tag("my-full-timeline")
public class MyFullTimeline extends FullCalendarScheduler {
   
	private static final long serialVersionUID = 1L;

	public MyFullTimeline(int entryLimit) {
        super(entryLimit);
    }
	
	public void addTooltips() {
		setEntryRenderCallback("" 
				+ "function(info) { "
				+ "		const instance = tippy(info.el); "
				+ "		instance.setContent(info.event.title);"
				//+ "		instance.setProps({"
				//+ "			position:'top', "
				//+ "			interactive:true, "
				//+ "			animation:'perspective', "
				//+ "			arrow:true, "
				//+ "			followCursor:'horizontal', "
				//+ "			theme:'translucent' "
				//+ "			}); "
				+ "		}"
				);
	}

	public void slideDays(int days) {
		JsonObject duration = Json.createObject();
		duration.put("days", days);
		
		getElement().callJsFunction("scrollToTime", duration);
	}
}
```

**Comment by stefanuebe** [comment]
I've added a sample to the directory's page on how to create a subcomponent utilizing the tippy lib.

**Comment by aetasoul** [comment]
Thanks! Maybe this afternoon or tomorrow morning I'll check it, if I can do it correctly and you are interested I can add a function to add tooltips and create a pull request

**Comment by aetasoul** [comment]
I've implemented the tooltip in my calendar class without problems, but I thinks it is better to not implement it as "standard" in your repo. Just keep the demo, so the people can add their own.

Maybe in future there should be an option to enable the tooltip and style it
