### ISSUE TITLE
Question: Cursor: Pointer for non editable entries

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#59]
Hi Stefan.

We have editable and non editable entries available in the calender. Editable ones hav the css class  .fc-event.fc-draggable which sets the pointer to them. Non editiable doesn't have this class. So the default cursor is shown. This is a bit missleading to the end users because the entry is still clickable which opens the entry details dialog. But it is not movable. Thats all correct.

Is it possible to maybe programmable add the css class .fc-event.fc-draggable to non editable entries to show the cursor pointer?

Thanks a lot for your time :)

Best, 
Kamuffe

**Comment by aetasoul** [comment]
Hi @kamuffe 

set event as: `editable:false`
then add
```javascript
eventRender: function(info) {
    if(!info.event.startEditable) {
        $(info.el).css('cursor','not-allowed');
        return;
    }
}
```

You can use `cursor:pointer` for the hand cusrsor.

**Comment by kamuffe** [comment]
@aetasoul thanks. this was working 👍

**Comment by kamuffe** [comment]
@aetasoul thanks. this was working 👍
