### ISSUE TITLE
Exception with Flow 12.0.0.beta1

### ISSUE THREAD

**Issue by heruan** [stefanuebe/vaadin_fullcalendar#6]
I'm trying this on Flow 12.0.0.beta1 (not sure if this is the cause) with this simple code:

```
layout.add(FullCalendarBuilder.create().build());
```

and I'm getting this client exception:

```
Uncaught TypeError: Cannot read property 'option' of undefined
    at HTMLElement.setOption (full-calendar.html:150)
```

**Comment by stefanuebe** [comment]
Hi. I tried it with the current beta1 and got it run normally. Can you give me some additional details about your setup? Have you tried it in production or dev mode?

**Comment by heruan** [comment]
I added only the `fullcalendar-scheduler` dependency which pulled an older version of `fullcalendar`. Adding both dependencies explicitly fixed the issue!
