### ISSUE TITLE
Missing element in setEntryRenderCallback

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#60]
Hi Stefan.

I tried out the setEntryRenderCallback to modify entry rendering. 
Code taken from youre example:
```
calendar.setEntryRenderCallback("" +
        "function(event, element) {" +
        "   console.log(event.title + 'X');" +
        "   element.css('color', 'red');" +
        "   return element; " +
        "}");
```
The function is called on the client side, but `element` is undefined. 
So a cannot modify it. Further more seems the sample to be outdated. To access the title I need the following snipped: `console.log(event.event.title + 'X');`

Is the call `element.css` still valid? I cannot find a reference at https://developer.mozilla.org/en-US/docs/Web/API/Element

Best,
Kamuffe

**Comment by aetasoul** [comment]
This addon is an integration of the FullCalendar 4 so I reference to the [official wiki](https://fullcalendar.io/docs/eventRender) for this version.

The `element `now is `el` the HTML element that is being rendered. It has already been populated with the correct time/title text. The eventRender callback function can modify element. For example, it can change its appearance via Element’s style object.

You can read [here](https://developer.mozilla.org/en-US/docs/Web/API/ElementCSSInlineStyle/style) about the styling.

```
calendar.setEntryRenderCallback("" +
        "function(info) {" +
        "   console.log(info.event.title + 'X');" +
        "   info.el.style.color = "red";" +
        "   return info.el; " +
        "}"
);
```
