### ISSUE TITLE
CurrentTime Indicator does not recognice UI Locale

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#65]
Hi Stefan.

In production the current time indicator displays the wrong time.

Server time:
```
# date
Fri Jul 10 06:28:19 CEST 2020
```

Java Time during startup:
```
[localhost-startStop-1] INFO com.myapp.ServletContextListener - Current Time: 2020-07-10T06:29:18.504877+02:00[Europe/Berlin]
[localhost-startStop-1] INFO com.myapp.ServletContextListener - Current Default Locale: en_GB
```

![calendar-time-indicator](https://user-images.githubusercontent.com/5285367/87117951-45bc7a00-c27a-11ea-8413-e73664a8e134.PNG)

During login we set the german locale like:
`UI.getCurrent().setLocale( Locale.GERMANY );`
We also set the locale during calender init: `fullCalendar.setLocale( Locale.GERMANY );`

As you can see the indicator is 2h behind the current time. So it seems that the time from the default locale (en_GB) is taken into account and not the one set during login.

Thanks a lot for your effort.
Best, Kamuffe

**Comment by stefanuebe** [comment]
Hi, I'm currently catched in a big project. I try to check out this issue as soon as possible. Sorry for the inconvenience.

**Comment by stefanuebe** [comment]
Hi Kamuffe,

what timezone have you set? Locale and timezone are separated and do not influence each other. Simple reason for that is, that I could have my locale set to Germany, but are currently sitting in Finland. In that case the Finish timezone is relevant for me, not the German one.

The two pictures show the result of the selected timezone and the independence to the locale.

![Annotation 2020-08-28 145231-a](https://user-images.githubusercontent.com/36725474/91562958-5b772300-e93e-11ea-8afd-cccc3796f120.png)

![Annotation 2020-08-28 145231](https://user-images.githubusercontent.com/36725474/91562959-5c0fb980-e93e-11ea-837e-1bcc2acf3fd5.png)
