### ISSUE TITLE
Calendar vertical scrollbar position wrong

### ISSUE THREAD

**Issue by aetasoul** [stefanuebe/vaadin_fullcalendar#66]
Hi Stefan,
Check the picture 

![Problem](https://user-images.githubusercontent.com/15131692/88893391-8e969b80-d246-11ea-98bd-aea3f100d492.JPG)

This problem appear each time that I open the page. It don't start from the top or from the bottom, but in some random position. This only happend if I populate the calendar with more then 19 entry, if I open it in a day with less values it's ok.

I need it to open and start from the top, any idea?

Thanks.

**Comment by aetasoul** [comment]
I have isolated the problem:

```javascript
_createInitOptions() {
        var options = super._createInitOptions();

        options.views = {};
        options.views.timeGridFourDay =
              {
                type: 'resourceTimeline',
                duration: { days: 75 }
              };
        options.
        options.defaultView = 'timeGridFourDay';

        return options;
    }
```

Running the calendar with this options make the vertical scrollbar appear in random position.

**Comment by stefanuebe** [comment]
Thanks for the PR :)

**Comment by stefanuebe** [comment]
Pushed version 2.3.3 containing the fix.
