### ISSUE TITLE
Drag resource event don't scroll the view

### ISSUE THREAD

**Issue by aetasoul** [stefanuebe/vaadin_fullcalendar#67]
Hi,
Running the demo I selected "RESOURCE_TIMELINE_YEAR" as view, dragging the event to the edge of the calendar don't scroll horizontal and vertical scrollbar, so I can't drag the event in days outside the current view.

![Cattura](https://user-images.githubusercontent.com/15131692/90001032-37a2b480-dc91-11ea-8096-b8f785a81bfb.JPG)

Running the demo for the Vaadin version 13 and fullcalendar 1.9.1 it works: [https://stefan.app.fi/fullcalendar-demo/](https://stefan.app.fi/fullcalendar-demo/)

The new version Vaadin 14 and FC 4.4.0 don't work: [https://stefan.app.fi/fullcalendar-demo2/](https://stefan.app.fi/fullcalendar-demo2/)

**Comment by stefanuebe** [comment]
Hi, I'm currently catched in a big project. I try to check out this issue as soon as possible. Sorry for the inconvenience.

**Comment by stefanuebe** [comment]
I've checked different settings now for some time. Normally it should do automatically, since the respective option "dragScroll" is true by default. But I cannot tell you, why it is not working. It might be related to the containers and their styling, but I couldn't find out yet what's the problem here.

**Comment by aetasoul** [comment]
Thank you @stefanuebe. I'll also try to investigate in the next days, if you have any update tell me, i'll do the same.

**Comment by aetasoul** [comment]
![image](https://user-images.githubusercontent.com/15131692/93992306-acd3d000-fd8d-11ea-94fb-d6bc331dcd43.png)

If you drag the event the scrollbar marked as **1** is not scrolling, but the scrollbar **2** is scrolling.

The problem is related to the `VerticalLayout` style, if you set the `overflow` property to `auto`, the scrollbar **2** also stop working.

**Comment by aetasoul** [comment]
I think the problem is here, if you try from the console to get the elements with class `fc-scroller` there is nothing `document.getElementsByClassName(".fc-scroller")` return `HTMLCollection []` also `document.getElementsByClassName("fc-scroller")`.

**Comment by stefanuebe** [comment]
Might be related to the shadow dom then. So maybe an issue for the FC itself

**Comment by aetasoul** [comment]
Seems that the interaction plugin is the cause

**Comment by aetasoul** [comment]
Confirmed from FC creator

https://github.com/fullcalendar/fullcalendar/issues/6428

**Comment by aetasoul** [comment]
The issue is present on both version V5 and V4, the creator (as you can see in the referenced issue fullcalendar/fullcalendar#6428) won't release a fix for the older version.
