### ISSUE TITLE
Event resizing not working on mobile

### ISSUE THREAD

**Issue by waver55** [stefanuebe/vaadin_fullcalendar#69]
Hey, I'm working with version 2.3.2 of the fullcalendar2 app. When you press and hold an event on iPhone the event becomes draggable, but as soon as I'm releasing the event, it is deselected. I was able to reproduce the behavior with the chrome debugger, selecting any mobile device. 
On the fullcalendar.io webpage the function works normally. I would be grateful if the problem could be resolved.

**Comment by stefanuebe** [comment]
Hey, I'm currently heavy loaded with work, but I try to have a deeper look into this as soon as possible.

**Comment by waver55** [comment]
Actually I did some research and found a bug that is very similar. https://github.com/fullcalendar/fullcalendar/issues/5706

**Comment by aetasoul** [comment]
I also have this problem on my application, maybe is better to update from fullcalendar@4.4.0 to fullcalendar@5.3.2? What do you think about that @stefanuebe ?

**Comment by stefanuebe** [comment]
Yes, that is definitely on the list, but will most likely happen at the beginning of next year, when my current project is over. Before that I have not really time to spend (since that will be a big piece of work again I guess - haven't checked it in detail yet, but the changes from 4 to 5 indicate that).

**Comment by aetasoul** [comment]
I have checked the upgrade guide and it is really easy and fast to do,  I have done it on my fork, the only remaining thing to do is to convert your custom CSS in `templateCalendarCss` and `templateSchedulerCss`.

**Comment by stefanuebe** [comment]
I'll try to give it a look nearby. Unfortunately the conversion is not the only thing, all the testing and following issues are the next one :D

**Comment by aetasoul** [comment]
Don't worry is not urgent, maybe you can create a separate branch for the upgrade to V5 where I can push my work untill now. In the next day I have some time to start convert CSS and implement multiple feature so it could be good to create a new branch so when I'm done I create a pull request on it 👍

**Comment by stefanuebe** [comment]
Created the branch.

Thanks for the work :) really appreciate that

**Comment by aetasoul** [comment]
Hi @waver55 we have finally released the V5 version as RC1, try it and let us know if you have any issue

**Comment by waver55** [comment]
Hey @aetasoul sorry for the late reply. I updated to the new Version, but it seems to make no difference regarding the event resizing. I wish I had an idea how to provide more information but im laggin the skill of debugging into those components.

**Comment by aetasoul** [comment]
Hi @waver55 seems that the problem is the shadow dom (I was able to replicate it using React shadow dom). There is an open issue, created by me, on the fullcalendar repo. I'm just waiting a confirmation from them, I'll update you as soon as possible :)

**Comment by aetasoul** [comment]
Hi @waver55 the full calendar creator confirmed the issue. You can take a look here to see the update status https://github.com/fullcalendar/fullcalendar/issues/6429 

We will also release a fix as soon as the release a fixed version

**Comment by aetasoul** [comment]
Hi @waver55 the bug is now fixed, we will release a new version as soon as possible. The issue is present on both version V5 and V4, the creator (as you can see in the referenced issue fullcalendar/fullcalendar#6429) won't release a fix for the older version.

**Comment by waver55** [comment]
Hey, thank you very much for the effort!

**Comment by aetasoul** [comment]
Hi @waver55 the version 3.0.2 is available on vaadin directory https://vaadin.com/directory/component/full-calendar-flow

Please update your version and let us know if this fix the problem :)
