### ISSUE TITLE
Use Instant instead of LocalDateTime for timezone support

### ISSUE THREAD

**Issue by heruan** [stefanuebe/vaadin_fullcalendar#7]
Fullcalendar has [timezone](https://fullcalendar.io/docs/timezone) support, but this component uses `LocalDateTime` as entry's start/end attributes. It would be useful to use `Instant` as attributes, so that they can easily be converter in whether timezone/offset the user needs to be displayed (e.g. when the calendar is used by users in different timezones).

**Comment by stefanuebe** [comment]
When you want to use the timezone support, wouldn't it make more sense to use ZonedDateTime classes instead (since the entries etc represent the client side entries)?

**Comment by heruan** [comment]
I think the entry itself shouldn't need to have a timezone, they just need to be placed in a specific point in time (i.e., an instant).

This way, you can have a selector for the timezone and display the calendar/scheduler in that specific timezone, without changing entries: just with `entry.getStart().atZone(...)`.

This would be specifically useful when a manager wants to see the schedule of employees spread between different timezone: entries won't need to change, you can just set the timezone and refresh.

**Comment by stefanuebe** [comment]
Setting a custom timezone (e.g. Europe/Berlin) requests the server side to parse the entry before sending / adding it to the FC instance. This means, that (at least internal) the FC server side needs to parse the values in either way and transfer it to a ZonedDT. 

Would result in something like:
```
// sets the UTC start and end of the entry
Entry.setStart/End(Instant)

// sets an optional timezone for the entry, UTC by default
Entry.setStartTimezone/EndTimezone(ZoneId)

// sets the timezone to be shown 
FullCalendar.setTimezone(ZoneId)
```

Example:
I create a new entry for 2020-01-01, 10:00 - 11:00, Berlin time. Would result in a server side entry with `9:00-10:00Z` plus the info that we have `MET`. 
Setting timezone "EET" at FullCalendar would display it at 11-12.

**Comment by heruan** [comment]
Thank you @stefanuebe for the explanation! As far as I understand, entries are eventually flushed to the client in JSON and start/end values need to be already in the desired timezone.

What I'd expect to be versatile enough when dealing with different timezones, is something like this:

```java
entry.setStart(Instant);
entry.setStop(Instant);

fullCalendar.setTimezone(ZoneId);
```

this will set the timezone for each entry, which will be used to produce "local" JSON start/end values:

```java
protected JsonObject toJson() {
    // ...
    LocalDateTime start = getStart().atZone(this.zone).toLocalDateTime();
    LocalDateTime end = getEnd().atZone(this.zone).toLocalDateTime();
    jsonObject.put("start", JsonUtils.toJsonValue(fullDayEvent ? start.toLocalDate() : start));
    jsonObject.put("end", JsonUtils.toJsonValue(fullDayEvent ? end.toLocalDate() : end));
   // ...
}
```
I don't expect to have a `Entry::setTimezone` public method (would be confusing), could be package private to be used only by `FullCalendar` when setting the zone.

**Comment by stefanuebe** [comment]
You can have a look on the branch "timezones", there is an experimental version of the new API, where Entries work with Instant. You can also set a Timezone on the calendar.

**Comment by heruan** [comment]
Looks *really* good! I'll test it ASAP. Thank you!

**Comment by stefanuebe** [comment]
I added API for usage of `LocalDateTime` (since some events work with LDT and to prevent a too large API break with the next version). The setter for start and end can handle both types, the getter now return `LocalDateTime` again plus  there are new getters (`getEndUTC`), which return the Instant.

The LocalDateTime is internally converted with the calendars timezone (or UTC as default).

**Comment by stefanuebe** [comment]
Updated addons to 1.6.0 / 1.1.0.
