### ISSUE TITLE
(TypeError) when using full calendar with a router layout in Vaadin starter app.

### ISSUE THREAD

**Issue by martinisraelsen** [stefanuebe/vaadin_fullcalendar#8]
Got this error when including the FullCalendar in Vaadin's Bakery App:

**(TypeError): undefined is not an object (evaluating 'this._calendar.option')**

The issue only appears if the view is using BakeryApp's MainView as the layout. If the view is using a different layout or no layout at all, the problem doesn't appear. Speculating that it may be caused by the javascript that's in the Polymer template for the MainView.

Experienced in 12.0.0.beta1 as well as 11.0.0

It *may* be the same or related to this issue: https://github.com/stefanuebe/vaadin_fullcalendar/issues/6

**Comment by stefanuebe** [comment]
Cause of this issue is, that the ready() function of the polymer element is called after the set and add methods and therefore the calendar instance is not initialized yet. Might be related to the parentLayout, I will check that.

**Comment by stefanuebe** [comment]
Can you please check the following:
1. Navigating via UI to your calendar page - this should work, since ready() is called first.
2. Navigating via Browser URL to your calendar page - this should not work, since ready() is called later
3. Navigating via UI (as in 1.) to your calendar page and refresh the page - this should not work as in 2.

**Comment by stefanuebe** [comment]
Ok, I don't know why yet, but when I remove the 
```
@Id("appNavigation")
private AppNavigation appNavigation;
```

from the main layout, it works for me in all 3 cases. Can you check that, too, please?

**Comment by stefanuebe** [comment]
Seems to be a general Flow problem: https://github.com/vaadin/flow/issues/4755.

Not using `@Id` flow field injection seem to solve the problem directly. I will check for a workaround until this one is fixed.
