### ISSUE TITLE
Updating extended properties doesn't work

### ISSUE THREAD

**Issue by Springrbua** [stefanuebe/vaadin_fullcalendar#81]
I am trying to show a selection indicator using a custom property. This custom property is set using `addExtendedProps` on the server side and I am using it inside the `EntryRenderCallback` to add a css class on selected entries.
However, when I print the properties on the client, they remain unchanged, even though the server sends them correctly.
The reason for this seems to be, that `updateEvnets` is using `setProp` to change the property (see https://github.com/stefanuebe/vaadin_fullcalendar/blob/master/addon/src/main/resources/META-INF/resources/frontend/full-calendar.js#L458).  This method only accepts known properties, for extended properties you should probably use [`setExtendedProp`](https://github.com/fullcalendar/fullcalendar/blob/d23d0927d67b60fa31b7f9faeb05d097edf68dfa/packages/common/src/api/EventApi.ts#L66).

**Comment by aetasoul** [comment]
Hi @Springrbua Thank you for reporting this issue. I'll investigate and release a fix for this as soon as possible.

**Comment by aetasoul** [comment]
Hi @Springrbua , can you share the code that cause the issue?

**Comment by Springrbua** [comment]
```
FullCalendar c = new FullCalendar();
c.addEntryClickedListener(e => {
  Entry oldSelected = this.selectedEntry;
  oldSelected.removeExtendedProps("selected");
  this.selectedEntry = e.getEntry();
  this.selectedEntry.addExtendedProps("selected", true);
  c.updateEntries(oldSelected, this.selectedEntry);
});
c.setEntryRenderCallback("" +
  "function (info) {" +
  "  if (info.event.extendedProps['selected'])" +
  "    info.el.classList.add('selected');"
  "  return info.el;" +
  "}"
);
```

**Comment by aetasoul** [comment]
I understand your problem, but not your code, can you share a reproducible example please?

**Comment by Springrbua** [comment]
Here is a reproduction with a starter created with https://start.vaadin.com/app/
I deleted all predefined views and added a single empty view named "Calendar".
This is the whole code of the `CalendarView`:

```
@Route(value = "Calendar")
@RouteAlias(value = "")
@PageTitle("Calendar")
public class CalendarView extends VerticalLayout {

    private Entry selected;

    public CalendarView() {
        FullCalendar fc = FullCalendarBuilder.create().build();
        Span spServerState = new Span("Entry 1: true");
        fc.changeView(CalendarViewImpl.DAY_GRID_MONTH);
        fc.setEntryRenderCallback("" +
            "function (info) {" +
            "   console.warn(info.event.title + ': ' + info.event.extendedProps['selected']);" +
            "	if (info.event.extendedProps['selected'])" +
            "		info.el.style.setProperty('border', '2px solid red');" +
            "	return info.el;" +
            "}");
        fc.addEntryClickedListener(e -> {
            Entry oldSelected = this.selected;
            oldSelected.removeExtendedProps("selected");
            this.selected = e.getEntry();
            this.selected.addExtendedProps("selected", true);
            fc.updateEntries(oldSelected, this.selected);
            spServerState.setText(
                oldSelected.getTitle() + ": " + oldSelected.getExtendedProps().get("selected") + "; " +
                selected.getTitle() + ": " + selected.getExtendedProps().get("selected") + "; "
            );
        });
        fc.setSizeFull();
        for (int i = 1; i < 10; i++) {
            LocalDate start = LocalDate.of(2021, 6, (int)(Math.random() * 29) + 1);
            LocalDate end = start.plusDays(1);
            Entry entry = new Entry(UUID.randomUUID().toString());
            entry.setColor("lightgreen");
            entry.setTitle("Entry " + i);
            entry.setStart(start.atStartOfDay());
            entry.setEnd(end.atTime(LocalTime.MAX));
            if (i == 1) {
                entry.addExtendedProps("selected", true);
                selected = entry;
            }
            fc.addEntry(entry);
        }

        setSizeFull();
        add(new HorizontalLayout(
            new Span("State on server:"),
            spServerState
        ));
        addAndExpand(fc);
    }
}
```

The selected entry gets a red 2px border. Entry 1 is selected by default and correctly shows the border. Clicking another entry should set remove the border from the old selected and add it to the new selected.
At the top, there is a text, showing the server side state of selected property (for old and new selected).
Also a console.warn prints the selected property for every entry on update.
The extended properties are only set on the client, when they are set before calling `FullCalendar.add(entry)`. Updating them doesn't work.

**Comment by Springrbua** [comment]
Yes, this is the expected result. Thank you

**Comment by aetasoul** [comment]
I'll push the changes, I have also implemented your example as demo in the project, that's ok for you?

**Comment by Springrbua** [comment]
Great thank you!

>I have also implemented your example as demo in the project, that's ok for you?

Yea sure :)

**Comment by stefanuebe** [comment]
Updated the directory.

**Comment by aetasoul** [comment]
Thank you!
