### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by Springrbua** [stefanuebe/vaadin_fullcalendar#82]
The methods `setHeader` and `setFooter` both take a `String` value. The documentation of fullcalendar instead takes an object with properties `start`, `center` and `end`.
Using `setOption("header", jObj)` seems to work just fine, but I was not able to get any result with `setHeader(String)`.
So I think, that `setHeader` and `setFooter` should accept a `JsonObject`, or event a class like `ToolbarOptions`, which includes properties `start`, `center` and `end`.
Also `getHeader` and `getFooter` causes a `ClassCastException` (see https://github.com/stefanuebe/vaadin_fullcalendar/blob/master/addon/src/main/java/org/vaadin/stefan/fullcalendar/FullCalendar.java#L882)

**Comment by aetasoul** [comment]
Hi @Springrbua maybe is better if you share the code you use when reporting issues. Thanks for the reporting

**Comment by Springrbua** [comment]
Sorry, here is the code:
```
FullCalendar c = new FullCalendar()
c.setLocale(locale);
c.setHeader(/*not sure what to enter here */);
JsonObject header = Json.createObject();
header.put("center", "title");
c.setOption("header", header);    // This works
```

**Comment by aetasoul** [comment]
Hi @Springrbua there a new version (2.4.1) released on vaadin directory, you can upgrade and test
