### ISSUE TITLE
update fullcalendar to v5

### ISSUE THREAD

**Issue by mperktold** [stefanuebe/vaadin_fullcalendar#83]
In fullcalendar v5, the API for customizing event rendering has been revisited: https://fullcalendar.io/docs/event-render-hooks

I would like to use the new hooks through this Vaadin wrapper, but it currently uses fullcalendar 4.4.2.

Is it possible to update fullcalendar to v5?
Note that it would be a breaking change.

**Comment by aetasoul** [comment]
Hi @mperktold there is a [branch ](https://github.com/stefanuebe/vaadin_fullcalendar/tree/v5) where we are working on the upgrade. [here](https://github.com/stefanuebe/vaadin_fullcalendar/issues/78) the open points to end the upgrade.

**Comment by mperktold** [comment]
I wasn't aware of that, thanks.

I tried the branch but I got exceptions, as already noted in the open points.

**Comment by aetasoul** [comment]
Hi @mperktold we have finally released the V5! Please check it out (master branch) and tell us any problem :)

Here the references for Vaadin Directory: https://vaadin.com/directory/component/full-calendar-flow
Scheduler: https://vaadin.com/directory/component/full-calendar-scheduler-flow
