### ISSUE TITLE
unable to set header

### ISSUE THREAD

**Issue by jmart1** [stefanuebe/vaadin_fullcalendar#91]
I'm using Vaadin 16.0.2 and Full Calendar 2.4.0.  I am trying to set the header on the calendar using the setHeader method, but it has no visible effect.

`        calendar.setHeader("{\"center\":\"next,title,prev\"}");`

Am I using it correctly?

Also, is there a call back for when the month (or week or day) changes?  Like from calling `calendar.next()`.  When the month changes I would like to have a call back where I can get the new value and the new start/end times.

Also, on the calendar there is no `getTitle` or `getView` methods.  How can I get the current title and view from the FullCalendar object?

**Comment by aetasoul** [comment]
Hi @jmart1 , the issue is solved?
