### ISSUE TITLE
Navigation / Applayout for Demo

### ISSUE THREAD

**Issue by stefanuebe** [stefanuebe/vaadin_fullcalendar#94]
There are multiple demos, but no centralized navigation to switch between them. The demo app should be extended by an AppLayout implementation providing router links for all demos.

**Comment by stefanuebe** [comment]
Added a first draft to the branch "demo". Some demos are good code examples, but not very visual, maybe we can add some "aha" effect content here or at least some descriptions what the benefit of this specific use case setting is.

**Comment by stefanuebe** [comment]
Also the extended properties demo is not working yet

**Comment by aetasoul** [comment]
Hi, I have totally reorganized the demo, changed the applayout for navigation and fixed the styling to perfectly fix desktop and mobile, I'll push it later on the demo branch.

**Comment by aetasoul** [comment]
The first preview is done, all the changes are pushed. Tomorrow I'll end the styling and after that start fixing some problems

**Comment by aetasoul** [comment]
> Also the extended properties demo is not working yet

About the extended prop demo I think we can change it to another example. The border update can be done with event click (that is better) and not with eventContent (that render all the events all the times that some changes happend)

**Comment by aetasoul** [comment]
@stefanuebe The issue can be closed or you need to do something else here?

**Comment by stefanuebe** [comment]
Nope :)
