### ISSUE TITLE
Layout does not resize to new container width after browser resizing

### ISSUE THREAD

**Issue by aetasoul** [stefanuebe/vaadin_fullcalendar#97]
There is a problem an all the demo with the applayout, open and close the left menu cause the calendar to not resize correctly.
This is an FC issue that I alredy reported here: https://github.com/fullcalendar/fullcalendar/issues/6407

**Comment by stefanuebe** [comment]
I am not sure if this still is an issue?

**Comment by aetasoul** [comment]
Can't test this for a while 😅

As I could see seems they found a workaround but not a real fix

**Comment by stefanuebe** [comment]
Should be fixed with 6.0.
