### ISSUE TITLE
Full demo not working 100 % on mobile devices

### ISSUE THREAD

**Issue by stefanuebe** [stefanuebe/vaadin_fullcalendar#98]
### Bug Description

* Open the demo on a mobile phone browser or use the dev tools to simulate one (e.g. Iphone X)
* Go to Full Demo
* Try to create a new entry or edit an existing one
* On new entry: popup only opens sometimes (in my case the date was always 4th to 10th of July, regardless of what I clicked)
* On existing entry: popup shows up normally, but does not save any changes

Tested on Galaxy S9 with Chrome and Windows 10 with Chrome.

**Comment by aetasoul** [comment]
To open the popup for new entry I have to keep selected the cell for ~2 seconds, but it always open.

The changes to the existing entry are saved, but not displayed, if I reopen the edited entry the changes are there, but not displayed on the calendar (maybe rerender event solve that?)

Tested on OnePlus 8 Pro with Chrome

I'll investigate.

**Comment by aetasoul** [comment]
FullDemo page:

Update Title, Description and Color does not take effect

Tooltip:

Same as FullDemo Page, plus can't see tooltip

**Comment by aetasoul** [comment]
Tooltip Page:

FC automatically put the description in the extendedProps

![image](https://user-images.githubusercontent.com/15131692/125908781-d7a5bb62-a16c-45cd-b7fb-e3328a2831f4.png)

It's not necessary to access the description with the new function getCustomProperty()

```javascript
callTooltip(info) {
        let description = FullCalendarWithTooltip.getCustomProperty(info.event, "description");
        if (description && !info.isMirror) {
            tippy(info.el, {
                // content: info.event.extendedProps.description
                theme: 'light',
                content: description
            });
        }
    }
```

just restore the old:

```javascript
callTooltip(info) {
    	if (info.event.extendedProps && info.event.extendedProps.description && !info.isMirror) {
            tippy(info.el, {
                theme: 'light',
                content: info.event.extendedProps.description
            });
        }
    }
```

**Comment by aetasoul** [comment]
About your point:
* On new entry: popup only opens sometimes (in my case the date was always 4th to 10th of July, regardless of what I clicked)

I can't reproduce the problem, but looking to the calendar, the only logical explaination is that for some reason it open the background event placed from 4th to 10th July

**Comment by aetasoul** [comment]
> About your point:
> 
> * On new entry: popup only opens sometimes (in my case the date was always 4th to 10th of July, regardless of what I clicked)
> 
> I can't reproduce the problem, but looking to the calendar, the only logical explaination is that for some reason it open the background event placed from 4th to 10th July

Reproduced only on mobile devices:

- Keep the date selected open the new event with correct date
- Single click open the EditDialog to edit the background event

```
calendar.addEntryClickedListener(event -> 
 new DemoDialog(calendar, (ResourceEntry) event.getEntry(), false).open()
);

((FullCalendarScheduler) calendar).addTimeslotsSelectedSchedulerListener((event) -> {
            ResourceEntry entry = new ResourceEntry();

            entry.setStart(event.getStartDateTimeUTC());
            entry.setEnd(event.getEndDateTimeUTC());
            entry.setAllDay(event.isAllDay());

            entry.setColor("dodgerblue");
            new DemoDialog(calendar, entry, true).open();
        });

```

On mobile devices:

addEntryClickedListener is fired and open the Dialog for the background event, addTimeslotsSelectedSchedulerListener is not fired because it require to keep the touch pressed for x seconds

On desktop:

Both are fired and the dialog open with addTimeslotsSelectedSchedulerListener but some times with addEntryClickedListener( that open the background event)

The eventClick (EntryClickedEvent) catch the click an all the events ignoring the RenderingMode

**Comment by aetasoul** [comment]
https://fullcalendar.io/docs/background-events

> ### Modifying Events
> The editable property of a calendar determines whether the events on it can be modified. However, Background Events are not editable. They can not be dragged or resized.

**Comment by aetasoul** [comment]
On FC V3 click on background event don't fire eventClick: https://codepen.io/aetasoul/pen/VwbxKQG
FC V4 click bg event fire eventClick: https://codepen.io/aetasoul/pen/KKmRgRz
FC V5 same as V4: https://codepen.io/aetasoul/pen/QWvrKxj

**Comment by stefanuebe** [comment]
I think for now it is ok then. If there are any specific, user case issues, we can handle those in a new, dedicated issue. Thanks :)
